// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livemap/v1/livemap.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Classification defines the types of BGP anomalies or events.
type Classification int32

const (
	Classification_CLASSIFICATION_UNSPECIFIED      Classification = 0
	Classification_CLASSIFICATION_BOGON            Classification = 1
	Classification_CLASSIFICATION_HIJACK           Classification = 2
	Classification_CLASSIFICATION_ROUTE_LEAK       Classification = 3
	Classification_CLASSIFICATION_OUTAGE           Classification = 4
	Classification_CLASSIFICATION_DDOS_MITIGATION  Classification = 5
	Classification_CLASSIFICATION_FLAP             Classification = 6
	Classification_CLASSIFICATION_PATH_HUNTING     Classification = 8
	Classification_CLASSIFICATION_DISCOVERY        Classification = 9
	Classification_CLASSIFICATION_MINOR_ROUTE_LEAK Classification = 10
)

// Enum value maps for Classification.
var (
	Classification_name = map[int32]string{
		0:  "CLASSIFICATION_UNSPECIFIED",
		1:  "CLASSIFICATION_BOGON",
		2:  "CLASSIFICATION_HIJACK",
		3:  "CLASSIFICATION_ROUTE_LEAK",
		4:  "CLASSIFICATION_OUTAGE",
		5:  "CLASSIFICATION_DDOS_MITIGATION",
		6:  "CLASSIFICATION_FLAP",
		8:  "CLASSIFICATION_PATH_HUNTING",
		9:  "CLASSIFICATION_DISCOVERY",
		10: "CLASSIFICATION_MINOR_ROUTE_LEAK",
	}
	Classification_value = map[string]int32{
		"CLASSIFICATION_UNSPECIFIED":      0,
		"CLASSIFICATION_BOGON":            1,
		"CLASSIFICATION_HIJACK":           2,
		"CLASSIFICATION_ROUTE_LEAK":       3,
		"CLASSIFICATION_OUTAGE":           4,
		"CLASSIFICATION_DDOS_MITIGATION":  5,
		"CLASSIFICATION_FLAP":             6,
		"CLASSIFICATION_PATH_HUNTING":     8,
		"CLASSIFICATION_DISCOVERY":        9,
		"CLASSIFICATION_MINOR_ROUTE_LEAK": 10,
	}
)

func (x Classification) Enum() *Classification {
	p := new(Classification)
	*p = x
	return p
}

func (x Classification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Classification) Descriptor() protoreflect.EnumDescriptor {
	return file_livemap_v1_livemap_proto_enumTypes[0].Descriptor()
}

func (Classification) Type() protoreflect.EnumType {
	return &file_livemap_v1_livemap_proto_enumTypes[0]
}

func (x Classification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Classification.Descriptor instead.
func (Classification) EnumDescriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{0}
}

// RPKIStatus defines the validation status of a prefix.
type RPKIStatus int32

const (
	RPKIStatus_RPKI_STATUS_UNSPECIFIED RPKIStatus = 0
	RPKIStatus_RPKI_STATUS_VALID       RPKIStatus = 1
	RPKIStatus_RPKI_STATUS_INVALID     RPKIStatus = 2
	RPKIStatus_RPKI_STATUS_NOT_FOUND   RPKIStatus = 3
)

// Enum value maps for RPKIStatus.
var (
	RPKIStatus_name = map[int32]string{
		0: "RPKI_STATUS_UNSPECIFIED",
		1: "RPKI_STATUS_VALID",
		2: "RPKI_STATUS_INVALID",
		3: "RPKI_STATUS_NOT_FOUND",
	}
	RPKIStatus_value = map[string]int32{
		"RPKI_STATUS_UNSPECIFIED": 0,
		"RPKI_STATUS_VALID":       1,
		"RPKI_STATUS_INVALID":     2,
		"RPKI_STATUS_NOT_FOUND":   3,
	}
)

func (x RPKIStatus) Enum() *RPKIStatus {
	p := new(RPKIStatus)
	*p = x
	return p
}

func (x RPKIStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPKIStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_livemap_v1_livemap_proto_enumTypes[1].Descriptor()
}

func (RPKIStatus) Type() protoreflect.EnumType {
	return &file_livemap_v1_livemap_proto_enumTypes[1]
}

func (x RPKIStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPKIStatus.Descriptor instead.
func (RPKIStatus) EnumDescriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{1}
}

// Aggregation method for alerts.
type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED     AlertType = 0
	AlertType_ALERT_TYPE_BY_LOCATION     AlertType = 1
	AlertType_ALERT_TYPE_BY_ASN          AlertType = 2
	AlertType_ALERT_TYPE_BY_COUNTRY      AlertType = 3
	AlertType_ALERT_TYPE_BY_ORGANIZATION AlertType = 4
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_BY_LOCATION",
		2: "ALERT_TYPE_BY_ASN",
		3: "ALERT_TYPE_BY_COUNTRY",
		4: "ALERT_TYPE_BY_ORGANIZATION",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED":     0,
		"ALERT_TYPE_BY_LOCATION":     1,
		"ALERT_TYPE_BY_ASN":          2,
		"ALERT_TYPE_BY_COUNTRY":      3,
		"ALERT_TYPE_BY_ORGANIZATION": 4,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_livemap_v1_livemap_proto_enumTypes[2].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_livemap_v1_livemap_proto_enumTypes[2]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{2}
}

// GeoData represents geographic coordinates.
type GeoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoData) Reset() {
	*x = GeoData{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoData) ProtoMessage() {}

func (x *GeoData) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoData.ProtoReflect.Descriptor instead.
func (*GeoData) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{0}
}

func (x *GeoData) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoData) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// AggregatedEvent represents multiple events aggregated by location and type.
type AggregatedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Geo            *GeoData               `protobuf:"bytes,1,opt,name=geo,proto3" json:"geo,omitempty"`
	Classification Classification         `protobuf:"varint,2,opt,name=classification,proto3,enum=livemap.v1.Classification" json:"classification,omitempty"`
	Count          uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregatedEvent) Reset() {
	*x = AggregatedEvent{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedEvent) ProtoMessage() {}

func (x *AggregatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedEvent.ProtoReflect.Descriptor instead.
func (*AggregatedEvent) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{1}
}

func (x *AggregatedEvent) GetGeo() *GeoData {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *AggregatedEvent) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *AggregatedEvent) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SubscribeEventsResponse is the response for event subscription.
type SubscribeEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AggregatedEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsResponse) Reset() {
	*x = SubscribeEventsResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsResponse) ProtoMessage() {}

func (x *SubscribeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeEventsResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeEventsResponse) GetEvents() []*AggregatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// SubscribeEventsRequest is the request for event subscription.
type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{3}
}

// GetSummaryRequest is the request for global summary statistics.
type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{4}
}

// ClassificationCount contains statistics for a specific classification.
type ClassificationCount struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Classification    Classification         `protobuf:"varint,1,opt,name=classification,proto3,enum=livemap.v1.Classification" json:"classification,omitempty"`
	Count             uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // windowed count for trendlines
	MessagesPerSecond float32                `protobuf:"fixed32,3,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`
	AsnCount          uint32                 `protobuf:"varint,4,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	PrefixCount       uint32                 `protobuf:"varint,5,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	Ipv4PrefixCount   uint32                 `protobuf:"varint,7,opt,name=ipv4_prefix_count,json=ipv4PrefixCount,proto3" json:"ipv4_prefix_count,omitempty"`
	Ipv6PrefixCount   uint32                 `protobuf:"varint,8,opt,name=ipv6_prefix_count,json=ipv6PrefixCount,proto3" json:"ipv6_prefix_count,omitempty"`
	Ipv4Count         uint64                 `protobuf:"varint,9,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	TotalCount        uint64                 `protobuf:"varint,10,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // global cumulative total
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassificationCount) Reset() {
	*x = ClassificationCount{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationCount) ProtoMessage() {}

func (x *ClassificationCount) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationCount.ProtoReflect.Descriptor instead.
func (*ClassificationCount) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{5}
}

func (x *ClassificationCount) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *ClassificationCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClassificationCount) GetMessagesPerSecond() float32 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *ClassificationCount) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *ClassificationCount) GetPrefixCount() uint32 {
	if x != nil {
		return x.PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv4PrefixCount() uint32 {
	if x != nil {
		return x.Ipv4PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv6PrefixCount() uint32 {
	if x != nil {
		return x.Ipv6PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv4Count() uint64 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *ClassificationCount) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CompositionEntry represents a segment of the event composition (e.g. BEACON, RESEARCH, ORGANIC).
type CompositionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositionEntry) Reset() {
	*x = CompositionEntry{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositionEntry) ProtoMessage() {}

func (x *CompositionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositionEntry.ProtoReflect.Descriptor instead.
func (*CompositionEntry) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{6}
}

func (x *CompositionEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CompositionEntry) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// GetSummaryResponse contains global and per-classification statistics.
type GetSummaryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessagesPerSecond    float32                `protobuf:"fixed32,1,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`
	AsnCount             uint32                 `protobuf:"varint,2,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	PrefixCount          uint32                 `protobuf:"varint,3,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	ClassificationCounts []*ClassificationCount `protobuf:"bytes,5,rep,name=classification_counts,json=classificationCounts,proto3" json:"classification_counts,omitempty"`
	Ipv4PrefixCount      uint32                 `protobuf:"varint,6,opt,name=ipv4_prefix_count,json=ipv4PrefixCount,proto3" json:"ipv4_prefix_count,omitempty"`
	Ipv6PrefixCount      uint32                 `protobuf:"varint,7,opt,name=ipv6_prefix_count,json=ipv6PrefixCount,proto3" json:"ipv6_prefix_count,omitempty"`
	Ipv4Count            uint64                 `protobuf:"varint,8,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	InputChannelLen      uint32                 `protobuf:"varint,9,opt,name=input_channel_len,json=inputChannelLen,proto3" json:"input_channel_len,omitempty"`
	InputChannelCapacity uint32                 `protobuf:"varint,10,opt,name=input_channel_capacity,json=inputChannelCapacity,proto3" json:"input_channel_capacity,omitempty"`
	MaxLagSeconds        uint32                 `protobuf:"varint,11,opt,name=max_lag_seconds,json=maxLagSeconds,proto3" json:"max_lag_seconds,omitempty"`
	LoadingHistorical    bool                   `protobuf:"varint,12,opt,name=loading_historical,json=loadingHistorical,proto3" json:"loading_historical,omitempty"`
	EventComposition     []*CompositionEntry    `protobuf:"bytes,13,rep,name=event_composition,json=eventComposition,proto3" json:"event_composition,omitempty"`
	LastRpkiStatus       RPKIStatus             `protobuf:"varint,14,opt,name=last_rpki_status,json=lastRpkiStatus,proto3,enum=livemap.v1.RPKIStatus" json:"last_rpki_status,omitempty"`
	// Top stats
	FlappiestNetworkStats []*FlappiestNetworkStats `protobuf:"bytes,23,rep,name=flappiest_network_stats,json=flappiestNetworkStats,proto3" json:"flappiest_network_stats,omitempty"`
	LargestOrgName        string                   `protobuf:"bytes,18,opt,name=largest_org_name,json=largestOrgName,proto3" json:"largest_org_name,omitempty"`
	LargestOrgIpv4Count   uint64                   `protobuf:"varint,19,opt,name=largest_org_ipv4_count,json=largestOrgIpv4Count,proto3" json:"largest_org_ipv4_count,omitempty"`
	RpkiValidIpv4         uint64                   `protobuf:"varint,20,opt,name=rpki_valid_ipv4,json=rpkiValidIpv4,proto3" json:"rpki_valid_ipv4,omitempty"`
	RpkiInvalidIpv4       uint64                   `protobuf:"varint,21,opt,name=rpki_invalid_ipv4,json=rpkiInvalidIpv4,proto3" json:"rpki_invalid_ipv4,omitempty"`
	RpkiNotFoundIpv4      uint64                   `protobuf:"varint,22,opt,name=rpki_not_found_ipv4,json=rpkiNotFoundIpv4,proto3" json:"rpki_not_found_ipv4,omitempty"`
	RpkiValidIpv6         uint64                   `protobuf:"varint,24,opt,name=rpki_valid_ipv6,json=rpkiValidIpv6,proto3" json:"rpki_valid_ipv6,omitempty"`
	RpkiInvalidIpv6       uint64                   `protobuf:"varint,25,opt,name=rpki_invalid_ipv6,json=rpkiInvalidIpv6,proto3" json:"rpki_invalid_ipv6,omitempty"`
	RpkiNotFoundIpv6      uint64                   `protobuf:"varint,26,opt,name=rpki_not_found_ipv6,json=rpkiNotFoundIpv6,proto3" json:"rpki_not_found_ipv6,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{7}
}

func (x *GetSummaryResponse) GetMessagesPerSecond() float32 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *GetSummaryResponse) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *GetSummaryResponse) GetPrefixCount() uint32 {
	if x != nil {
		return x.PrefixCount
	}
	return 0
}

func (x *GetSummaryResponse) GetClassificationCounts() []*ClassificationCount {
	if x != nil {
		return x.ClassificationCounts
	}
	return nil
}

func (x *GetSummaryResponse) GetIpv4PrefixCount() uint32 {
	if x != nil {
		return x.Ipv4PrefixCount
	}
	return 0
}

func (x *GetSummaryResponse) GetIpv6PrefixCount() uint32 {
	if x != nil {
		return x.Ipv6PrefixCount
	}
	return 0
}

func (x *GetSummaryResponse) GetIpv4Count() uint64 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *GetSummaryResponse) GetInputChannelLen() uint32 {
	if x != nil {
		return x.InputChannelLen
	}
	return 0
}

func (x *GetSummaryResponse) GetInputChannelCapacity() uint32 {
	if x != nil {
		return x.InputChannelCapacity
	}
	return 0
}

func (x *GetSummaryResponse) GetMaxLagSeconds() uint32 {
	if x != nil {
		return x.MaxLagSeconds
	}
	return 0
}

func (x *GetSummaryResponse) GetLoadingHistorical() bool {
	if x != nil {
		return x.LoadingHistorical
	}
	return false
}

func (x *GetSummaryResponse) GetEventComposition() []*CompositionEntry {
	if x != nil {
		return x.EventComposition
	}
	return nil
}

func (x *GetSummaryResponse) GetLastRpkiStatus() RPKIStatus {
	if x != nil {
		return x.LastRpkiStatus
	}
	return RPKIStatus_RPKI_STATUS_UNSPECIFIED
}

func (x *GetSummaryResponse) GetFlappiestNetworkStats() []*FlappiestNetworkStats {
	if x != nil {
		return x.FlappiestNetworkStats
	}
	return nil
}

func (x *GetSummaryResponse) GetLargestOrgName() string {
	if x != nil {
		return x.LargestOrgName
	}
	return ""
}

func (x *GetSummaryResponse) GetLargestOrgIpv4Count() uint64 {
	if x != nil {
		return x.LargestOrgIpv4Count
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiValidIpv4() uint64 {
	if x != nil {
		return x.RpkiValidIpv4
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiInvalidIpv4() uint64 {
	if x != nil {
		return x.RpkiInvalidIpv4
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiNotFoundIpv4() uint64 {
	if x != nil {
		return x.RpkiNotFoundIpv4
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiValidIpv6() uint64 {
	if x != nil {
		return x.RpkiValidIpv6
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiInvalidIpv6() uint64 {
	if x != nil {
		return x.RpkiInvalidIpv6
	}
	return 0
}

func (x *GetSummaryResponse) GetRpkiNotFoundIpv6() uint64 {
	if x != nil {
		return x.RpkiNotFoundIpv6
	}
	return 0
}

type FlappiestNetworkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	NetworkName   string                 `protobuf:"bytes,2,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	EventRate     float32                `protobuf:"fixed32,3,opt,name=event_rate,json=eventRate,proto3" json:"event_rate,omitempty"`
	FlapCount     uint32                 `protobuf:"varint,4,opt,name=flap_count,json=flapCount,proto3" json:"flap_count,omitempty"` // cumulative count in the last 24 hours
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlappiestNetworkStats) Reset() {
	*x = FlappiestNetworkStats{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlappiestNetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlappiestNetworkStats) ProtoMessage() {}

func (x *FlappiestNetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlappiestNetworkStats.ProtoReflect.Descriptor instead.
func (*FlappiestNetworkStats) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{8}
}

func (x *FlappiestNetworkStats) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *FlappiestNetworkStats) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *FlappiestNetworkStats) GetEventRate() float32 {
	if x != nil {
		return x.EventRate
	}
	return 0
}

func (x *FlappiestNetworkStats) GetFlapCount() uint32 {
	if x != nil {
		return x.FlapCount
	}
	return 0
}

func (x *FlappiestNetworkStats) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// LeakDetail contains information specific to route leaks.
type LeakDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeakType         uint32                 `protobuf:"varint,1,opt,name=leak_type,json=leakType,proto3" json:"leak_type,omitempty"`
	LeakerAsn        uint32                 `protobuf:"varint,2,opt,name=leaker_asn,json=leakerAsn,proto3" json:"leaker_asn,omitempty"`
	VictimAsn        uint32                 `protobuf:"varint,3,opt,name=victim_asn,json=victimAsn,proto3" json:"victim_asn,omitempty"`
	LeakerAsName     string                 `protobuf:"bytes,4,opt,name=leaker_as_name,json=leakerAsName,proto3" json:"leaker_as_name,omitempty"`
	VictimAsName     string                 `protobuf:"bytes,5,opt,name=victim_as_name,json=victimAsName,proto3" json:"victim_as_name,omitempty"`
	LeakerRpkiStatus RPKIStatus             `protobuf:"varint,6,opt,name=leaker_rpki_status,json=leakerRpkiStatus,proto3,enum=livemap.v1.RPKIStatus" json:"leaker_rpki_status,omitempty"`
	VictimRpkiStatus RPKIStatus             `protobuf:"varint,7,opt,name=victim_rpki_status,json=victimRpkiStatus,proto3,enum=livemap.v1.RPKIStatus" json:"victim_rpki_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeakDetail) Reset() {
	*x = LeakDetail{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakDetail) ProtoMessage() {}

func (x *LeakDetail) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakDetail.ProtoReflect.Descriptor instead.
func (*LeakDetail) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{9}
}

func (x *LeakDetail) GetLeakType() uint32 {
	if x != nil {
		return x.LeakType
	}
	return 0
}

func (x *LeakDetail) GetLeakerAsn() uint32 {
	if x != nil {
		return x.LeakerAsn
	}
	return 0
}

func (x *LeakDetail) GetVictimAsn() uint32 {
	if x != nil {
		return x.VictimAsn
	}
	return 0
}

func (x *LeakDetail) GetLeakerAsName() string {
	if x != nil {
		return x.LeakerAsName
	}
	return ""
}

func (x *LeakDetail) GetVictimAsName() string {
	if x != nil {
		return x.VictimAsName
	}
	return ""
}

func (x *LeakDetail) GetLeakerRpkiStatus() RPKIStatus {
	if x != nil {
		return x.LeakerRpkiStatus
	}
	return RPKIStatus_RPKI_STATUS_UNSPECIFIED
}

func (x *LeakDetail) GetVictimRpkiStatus() RPKIStatus {
	if x != nil {
		return x.VictimRpkiStatus
	}
	return RPKIStatus_RPKI_STATUS_UNSPECIFIED
}

// StateTransition represents a change in classification for a prefix.
type StateTransition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncidentId     string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Prefix         string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Asn            uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	AsName         string                 `protobuf:"bytes,4,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Geo            *GeoData               `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Country        string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	NewState       Classification         `protobuf:"varint,8,opt,name=new_state,json=newState,proto3,enum=livemap.v1.Classification" json:"new_state,omitempty"`
	OldState       Classification         `protobuf:"varint,9,opt,name=old_state,json=oldState,proto3,enum=livemap.v1.Classification" json:"old_state,omitempty"`
	StartTime      int64                  `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LeakDetail     *LeakDetail            `protobuf:"bytes,12,opt,name=leak_detail,json=leakDetail,proto3" json:"leak_detail,omitempty"`
	Organization   string                 `protobuf:"bytes,13,opt,name=organization,proto3" json:"organization,omitempty"`
	AnomalyDetails string                 `protobuf:"bytes,14,opt,name=anomaly_details,json=anomalyDetails,proto3" json:"anomaly_details,omitempty"`
	RpkiStatus     RPKIStatus             `protobuf:"varint,15,opt,name=rpki_status,json=rpkiStatus,proto3,enum=livemap.v1.RPKIStatus" json:"rpki_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateTransition) Reset() {
	*x = StateTransition{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransition) ProtoMessage() {}

func (x *StateTransition) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransition.ProtoReflect.Descriptor instead.
func (*StateTransition) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{10}
}

func (x *StateTransition) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *StateTransition) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *StateTransition) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *StateTransition) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *StateTransition) GetGeo() *GeoData {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *StateTransition) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StateTransition) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *StateTransition) GetNewState() Classification {
	if x != nil {
		return x.NewState
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *StateTransition) GetOldState() Classification {
	if x != nil {
		return x.OldState
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *StateTransition) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StateTransition) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StateTransition) GetLeakDetail() *LeakDetail {
	if x != nil {
		return x.LeakDetail
	}
	return nil
}

func (x *StateTransition) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *StateTransition) GetAnomalyDetails() string {
	if x != nil {
		return x.AnomalyDetails
	}
	return ""
}

func (x *StateTransition) GetRpkiStatus() RPKIStatus {
	if x != nil {
		return x.RpkiStatus
	}
	return RPKIStatus_RPKI_STATUS_UNSPECIFIED
}

type AlertLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Lat           float32                `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,4,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusKm      float32                `protobuf:"fixed32,5,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertLocation) Reset() {
	*x = AlertLocation{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertLocation) ProtoMessage() {}

func (x *AlertLocation) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertLocation.ProtoReflect.Descriptor instead.
func (*AlertLocation) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{11}
}

func (x *AlertLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AlertLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AlertLocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AlertLocation) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *AlertLocation) GetRadiusKm() float32 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

// Alert represents a significant spike in anomalies.
type Alert struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AlertType            AlertType              `protobuf:"varint,1,opt,name=alert_type,json=alertType,proto3,enum=livemap.v1.AlertType" json:"alert_type,omitempty"`
	Location             *AlertLocation         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // Can be a radius, a city name, or just a generic string representing the area.
	Asn                  uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	Country              string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Classification       Classification         `protobuf:"varint,5,opt,name=classification,proto3,enum=livemap.v1.Classification" json:"classification,omitempty"`
	EventsCount          uint32                 `protobuf:"varint,6,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	Delta                int32                  `protobuf:"varint,7,opt,name=delta,proto3" json:"delta,omitempty"` // Change in count over the last 5 minutes
	Timestamp            int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ImpactedIpv4Ips      uint64                 `protobuf:"varint,9,opt,name=impacted_ipv4_ips,json=impactedIpv4Ips,proto3" json:"impacted_ipv4_ips,omitempty"`
	ImpactedIpv6Prefixes uint32                 `protobuf:"varint,10,opt,name=impacted_ipv6_prefixes,json=impactedIpv6Prefixes,proto3" json:"impacted_ipv6_prefixes,omitempty"`
	PercentageIncrease   float32                `protobuf:"fixed32,11,opt,name=percentage_increase,json=percentageIncrease,proto3" json:"percentage_increase,omitempty"`
	AsName               string                 `protobuf:"bytes,12,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Organization         string                 `protobuf:"bytes,13,opt,name=organization,proto3" json:"organization,omitempty"`
	AsnCount             uint32                 `protobuf:"varint,14,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	AnomalyScore         float32                `protobuf:"fixed32,15,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	SampleEvents         []*StateTransition     `protobuf:"bytes,16,rep,name=sample_events,json=sampleEvents,proto3" json:"sample_events,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{12}
}

func (x *Alert) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *Alert) GetLocation() *AlertLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Alert) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Alert) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Alert) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *Alert) GetEventsCount() uint32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *Alert) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Alert) GetImpactedIpv4Ips() uint64 {
	if x != nil {
		return x.ImpactedIpv4Ips
	}
	return 0
}

func (x *Alert) GetImpactedIpv6Prefixes() uint32 {
	if x != nil {
		return x.ImpactedIpv6Prefixes
	}
	return 0
}

func (x *Alert) GetPercentageIncrease() float32 {
	if x != nil {
		return x.PercentageIncrease
	}
	return 0
}

func (x *Alert) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *Alert) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Alert) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *Alert) GetAnomalyScore() float32 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *Alert) GetSampleEvents() []*StateTransition {
	if x != nil {
		return x.SampleEvents
	}
	return nil
}

type StreamAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAlertsRequest) Reset() {
	*x = StreamAlertsRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAlertsRequest) ProtoMessage() {}

func (x *StreamAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAlertsRequest.ProtoReflect.Descriptor instead.
func (*StreamAlertsRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{13}
}

type StreamAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAlertsResponse) Reset() {
	*x = StreamAlertsResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAlertsResponse) ProtoMessage() {}

func (x *StreamAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAlertsResponse.ProtoReflect.Descriptor instead.
func (*StreamAlertsResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{14}
}

func (x *StreamAlertsResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type GetRecentAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAlertsRequest) Reset() {
	*x = GetRecentAlertsRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAlertsRequest) ProtoMessage() {}

func (x *GetRecentAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentAlertsRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{15}
}

type GetRecentAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAlertsResponse) Reset() {
	*x = GetRecentAlertsResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAlertsResponse) ProtoMessage() {}

func (x *GetRecentAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentAlertsResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{16}
}

func (x *GetRecentAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// StreamStateTransitionsRequest is the request for state transition updates.
type StreamStateTransitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetStates  []Classification       `protobuf:"varint,1,rep,packed,name=target_states,json=targetStates,proto3,enum=livemap.v1.Classification" json:"target_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateTransitionsRequest) Reset() {
	*x = StreamStateTransitionsRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateTransitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateTransitionsRequest) ProtoMessage() {}

func (x *StreamStateTransitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateTransitionsRequest.ProtoReflect.Descriptor instead.
func (*StreamStateTransitionsRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{17}
}

func (x *StreamStateTransitionsRequest) GetTargetStates() []Classification {
	if x != nil {
		return x.TargetStates
	}
	return nil
}

// StreamStateTransitionsResponse is the response for state transition updates.
type StreamStateTransitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transition    *StateTransition       `protobuf:"bytes,1,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateTransitionsResponse) Reset() {
	*x = StreamStateTransitionsResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateTransitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateTransitionsResponse) ProtoMessage() {}

func (x *StreamStateTransitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateTransitionsResponse.ProtoReflect.Descriptor instead.
func (*StreamStateTransitionsResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{18}
}

func (x *StreamStateTransitionsResponse) GetTransition() *StateTransition {
	if x != nil {
		return x.Transition
	}
	return nil
}

type GetFlappiestNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlappiestNetworksRequest) Reset() {
	*x = GetFlappiestNetworksRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlappiestNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlappiestNetworksRequest) ProtoMessage() {}

func (x *GetFlappiestNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlappiestNetworksRequest.ProtoReflect.Descriptor instead.
func (*GetFlappiestNetworksRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{19}
}

func (x *GetFlappiestNetworksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFlappiestNetworksResponse struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	FlappiestNetworks []*FlappiestNetworkStats `protobuf:"bytes,1,rep,name=flappiest_networks,json=flappiestNetworks,proto3" json:"flappiest_networks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFlappiestNetworksResponse) Reset() {
	*x = GetFlappiestNetworksResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlappiestNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlappiestNetworksResponse) ProtoMessage() {}

func (x *GetFlappiestNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlappiestNetworksResponse.ProtoReflect.Descriptor instead.
func (*GetFlappiestNetworksResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{20}
}

func (x *GetFlappiestNetworksResponse) GetFlappiestNetworks() []*FlappiestNetworkStats {
	if x != nil {
		return x.FlappiestNetworks
	}
	return nil
}

type StreamPrefixSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPrefixSnapshotsRequest) Reset() {
	*x = StreamPrefixSnapshotsRequest{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPrefixSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPrefixSnapshotsRequest) ProtoMessage() {}

func (x *StreamPrefixSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPrefixSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*StreamPrefixSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{21}
}

type StreamPrefixSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*PrefixSnapshot      `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPrefixSnapshotsResponse) Reset() {
	*x = StreamPrefixSnapshotsResponse{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPrefixSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPrefixSnapshotsResponse) ProtoMessage() {}

func (x *StreamPrefixSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPrefixSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*StreamPrefixSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{22}
}

func (x *StreamPrefixSnapshotsResponse) GetSnapshots() []*PrefixSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type PrefixSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prefix         string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Classification Classification         `protobuf:"varint,2,opt,name=classification,proto3,enum=livemap.v1.Classification" json:"classification,omitempty"`
	Asn            uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	LastUpdateTs   int64                  `protobuf:"varint,4,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	TotalEvents    uint32                 `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrefixSnapshot) Reset() {
	*x = PrefixSnapshot{}
	mi := &file_livemap_v1_livemap_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixSnapshot) ProtoMessage() {}

func (x *PrefixSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_livemap_v1_livemap_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixSnapshot.ProtoReflect.Descriptor instead.
func (*PrefixSnapshot) Descriptor() ([]byte, []int) {
	return file_livemap_v1_livemap_proto_rawDescGZIP(), []int{23}
}

func (x *PrefixSnapshot) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixSnapshot) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_CLASSIFICATION_UNSPECIFIED
}

func (x *PrefixSnapshot) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *PrefixSnapshot) GetLastUpdateTs() int64 {
	if x != nil {
		return x.LastUpdateTs
	}
	return 0
}

func (x *PrefixSnapshot) GetTotalEvents() uint32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

var File_livemap_v1_livemap_proto protoreflect.FileDescriptor

const file_livemap_v1_livemap_proto_rawDesc = "" +
	"\n" +
	"\x18livemap/v1/livemap.proto\x12\n" +
	"livemap.v1\"-\n" +
	"\aGeoData\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\"\x92\x01\n" +
	"\x0fAggregatedEvent\x12%\n" +
	"\x03geo\x18\x01 \x01(\v2\x13.livemap.v1.GeoDataR\x03geo\x12B\n" +
	"\x0eclassification\x18\x02 \x01(\x0e2\x1a.livemap.v1.ClassificationR\x0eclassification\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"N\n" +
	"\x17SubscribeEventsResponse\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.livemap.v1.AggregatedEventR\x06events\"\x18\n" +
	"\x16SubscribeEventsRequest\"\x13\n" +
	"\x11GetSummaryRequest\"\xf7\x02\n" +
	"\x13ClassificationCount\x12B\n" +
	"\x0eclassification\x18\x01 \x01(\x0e2\x1a.livemap.v1.ClassificationR\x0eclassification\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12.\n" +
	"\x13messages_per_second\x18\x03 \x01(\x02R\x11messagesPerSecond\x12\x1b\n" +
	"\tasn_count\x18\x04 \x01(\rR\basnCount\x12!\n" +
	"\fprefix_count\x18\x05 \x01(\rR\vprefixCount\x12*\n" +
	"\x11ipv4_prefix_count\x18\a \x01(\rR\x0fipv4PrefixCount\x12*\n" +
	"\x11ipv6_prefix_count\x18\b \x01(\rR\x0fipv6PrefixCount\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\t \x01(\x04R\tipv4Count\x12\x1f\n" +
	"\vtotal_count\x18\n" +
	" \x01(\x04R\n" +
	"totalCount\"F\n" +
	"\x10CompositionEntry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\"\xd7\b\n" +
	"\x12GetSummaryResponse\x12.\n" +
	"\x13messages_per_second\x18\x01 \x01(\x02R\x11messagesPerSecond\x12\x1b\n" +
	"\tasn_count\x18\x02 \x01(\rR\basnCount\x12!\n" +
	"\fprefix_count\x18\x03 \x01(\rR\vprefixCount\x12T\n" +
	"\x15classification_counts\x18\x05 \x03(\v2\x1f.livemap.v1.ClassificationCountR\x14classificationCounts\x12*\n" +
	"\x11ipv4_prefix_count\x18\x06 \x01(\rR\x0fipv4PrefixCount\x12*\n" +
	"\x11ipv6_prefix_count\x18\a \x01(\rR\x0fipv6PrefixCount\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\b \x01(\x04R\tipv4Count\x12*\n" +
	"\x11input_channel_len\x18\t \x01(\rR\x0finputChannelLen\x124\n" +
	"\x16input_channel_capacity\x18\n" +
	" \x01(\rR\x14inputChannelCapacity\x12&\n" +
	"\x0fmax_lag_seconds\x18\v \x01(\rR\rmaxLagSeconds\x12-\n" +
	"\x12loading_historical\x18\f \x01(\bR\x11loadingHistorical\x12I\n" +
	"\x11event_composition\x18\r \x03(\v2\x1c.livemap.v1.CompositionEntryR\x10eventComposition\x12@\n" +
	"\x10last_rpki_status\x18\x0e \x01(\x0e2\x16.livemap.v1.RPKIStatusR\x0elastRpkiStatus\x12Y\n" +
	"\x17flappiest_network_stats\x18\x17 \x03(\v2!.livemap.v1.FlappiestNetworkStatsR\x15flappiestNetworkStats\x12(\n" +
	"\x10largest_org_name\x18\x12 \x01(\tR\x0elargestOrgName\x123\n" +
	"\x16largest_org_ipv4_count\x18\x13 \x01(\x04R\x13largestOrgIpv4Count\x12&\n" +
	"\x0frpki_valid_ipv4\x18\x14 \x01(\x04R\rrpkiValidIpv4\x12*\n" +
	"\x11rpki_invalid_ipv4\x18\x15 \x01(\x04R\x0frpkiInvalidIpv4\x12-\n" +
	"\x13rpki_not_found_ipv4\x18\x16 \x01(\x04R\x10rpkiNotFoundIpv4\x12&\n" +
	"\x0frpki_valid_ipv6\x18\x18 \x01(\x04R\rrpkiValidIpv6\x12*\n" +
	"\x11rpki_invalid_ipv6\x18\x19 \x01(\x04R\x0frpkiInvalidIpv6\x12-\n" +
	"\x13rpki_not_found_ipv6\x18\x1a \x01(\x04R\x10rpkiNotFoundIpv6\"\xa2\x01\n" +
	"\x15FlappiestNetworkStats\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12!\n" +
	"\fnetwork_name\x18\x02 \x01(\tR\vnetworkName\x12\x1d\n" +
	"\n" +
	"event_rate\x18\x03 \x01(\x02R\teventRate\x12\x1d\n" +
	"\n" +
	"flap_count\x18\x04 \x01(\rR\tflapCount\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\"\xbf\x02\n" +
	"\n" +
	"LeakDetail\x12\x1b\n" +
	"\tleak_type\x18\x01 \x01(\rR\bleakType\x12\x1d\n" +
	"\n" +
	"leaker_asn\x18\x02 \x01(\rR\tleakerAsn\x12\x1d\n" +
	"\n" +
	"victim_asn\x18\x03 \x01(\rR\tvictimAsn\x12$\n" +
	"\x0eleaker_as_name\x18\x04 \x01(\tR\fleakerAsName\x12$\n" +
	"\x0evictim_as_name\x18\x05 \x01(\tR\fvictimAsName\x12D\n" +
	"\x12leaker_rpki_status\x18\x06 \x01(\x0e2\x16.livemap.v1.RPKIStatusR\x10leakerRpkiStatus\x12D\n" +
	"\x12victim_rpki_status\x18\a \x01(\x0e2\x16.livemap.v1.RPKIStatusR\x10victimRpkiStatus\"\xb5\x04\n" +
	"\x0fStateTransition\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12\x17\n" +
	"\aas_name\x18\x04 \x01(\tR\x06asName\x12%\n" +
	"\x03geo\x18\x05 \x01(\v2\x13.livemap.v1.GeoDataR\x03geo\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x127\n" +
	"\tnew_state\x18\b \x01(\x0e2\x1a.livemap.v1.ClassificationR\bnewState\x127\n" +
	"\told_state\x18\t \x01(\x0e2\x1a.livemap.v1.ClassificationR\boldState\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x127\n" +
	"\vleak_detail\x18\f \x01(\v2\x16.livemap.v1.LeakDetailR\n" +
	"leakDetail\x12\"\n" +
	"\forganization\x18\r \x01(\tR\forganization\x12'\n" +
	"\x0fanomaly_details\x18\x0e \x01(\tR\x0eanomalyDetails\x127\n" +
	"\vrpki_status\x18\x0f \x01(\x0e2\x16.livemap.v1.RPKIStatusR\n" +
	"rpkiStatus\"~\n" +
	"\rAlertLocation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x02R\x03lon\x12\x1b\n" +
	"\tradius_km\x18\x05 \x01(\x02R\bradiusKm\"\x8f\x05\n" +
	"\x05Alert\x124\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\x0e2\x15.livemap.v1.AlertTypeR\talertType\x125\n" +
	"\blocation\x18\x02 \x01(\v2\x19.livemap.v1.AlertLocationR\blocation\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12B\n" +
	"\x0eclassification\x18\x05 \x01(\x0e2\x1a.livemap.v1.ClassificationR\x0eclassification\x12!\n" +
	"\fevents_count\x18\x06 \x01(\rR\veventsCount\x12\x14\n" +
	"\x05delta\x18\a \x01(\x05R\x05delta\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12*\n" +
	"\x11impacted_ipv4_ips\x18\t \x01(\x04R\x0fimpactedIpv4Ips\x124\n" +
	"\x16impacted_ipv6_prefixes\x18\n" +
	" \x01(\rR\x14impactedIpv6Prefixes\x12/\n" +
	"\x13percentage_increase\x18\v \x01(\x02R\x12percentageIncrease\x12\x17\n" +
	"\aas_name\x18\f \x01(\tR\x06asName\x12\"\n" +
	"\forganization\x18\r \x01(\tR\forganization\x12\x1b\n" +
	"\tasn_count\x18\x0e \x01(\rR\basnCount\x12#\n" +
	"\ranomaly_score\x18\x0f \x01(\x02R\fanomalyScore\x12@\n" +
	"\rsample_events\x18\x10 \x03(\v2\x1b.livemap.v1.StateTransitionR\fsampleEvents\"\x15\n" +
	"\x13StreamAlertsRequest\"?\n" +
	"\x14StreamAlertsResponse\x12'\n" +
	"\x05alert\x18\x01 \x01(\v2\x11.livemap.v1.AlertR\x05alert\"\x18\n" +
	"\x16GetRecentAlertsRequest\"D\n" +
	"\x17GetRecentAlertsResponse\x12)\n" +
	"\x06alerts\x18\x01 \x03(\v2\x11.livemap.v1.AlertR\x06alerts\"`\n" +
	"\x1dStreamStateTransitionsRequest\x12?\n" +
	"\rtarget_states\x18\x01 \x03(\x0e2\x1a.livemap.v1.ClassificationR\ftargetStates\"]\n" +
	"\x1eStreamStateTransitionsResponse\x12;\n" +
	"\n" +
	"transition\x18\x01 \x01(\v2\x1b.livemap.v1.StateTransitionR\n" +
	"transition\"3\n" +
	"\x1bGetFlappiestNetworksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"p\n" +
	"\x1cGetFlappiestNetworksResponse\x12P\n" +
	"\x12flappiest_networks\x18\x01 \x03(\v2!.livemap.v1.FlappiestNetworkStatsR\x11flappiestNetworks\"\x1e\n" +
	"\x1cStreamPrefixSnapshotsRequest\"Y\n" +
	"\x1dStreamPrefixSnapshotsResponse\x128\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1a.livemap.v1.PrefixSnapshotR\tsnapshots\"\xc7\x01\n" +
	"\x0ePrefixSnapshot\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12B\n" +
	"\x0eclassification\x18\x02 \x01(\x0e2\x1a.livemap.v1.ClassificationR\x0eclassification\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12$\n" +
	"\x0elast_update_ts\x18\x04 \x01(\x03R\flastUpdateTs\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\rR\vtotalEvents*\xc0\x02\n" +
	"\x0eClassification\x12\x1e\n" +
	"\x1aCLASSIFICATION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CLASSIFICATION_BOGON\x10\x01\x12\x19\n" +
	"\x15CLASSIFICATION_HIJACK\x10\x02\x12\x1d\n" +
	"\x19CLASSIFICATION_ROUTE_LEAK\x10\x03\x12\x19\n" +
	"\x15CLASSIFICATION_OUTAGE\x10\x04\x12\"\n" +
	"\x1eCLASSIFICATION_DDOS_MITIGATION\x10\x05\x12\x17\n" +
	"\x13CLASSIFICATION_FLAP\x10\x06\x12\x1f\n" +
	"\x1bCLASSIFICATION_PATH_HUNTING\x10\b\x12\x1c\n" +
	"\x18CLASSIFICATION_DISCOVERY\x10\t\x12#\n" +
	"\x1fCLASSIFICATION_MINOR_ROUTE_LEAK\x10\n" +
	"*t\n" +
	"\n" +
	"RPKIStatus\x12\x1b\n" +
	"\x17RPKI_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RPKI_STATUS_VALID\x10\x01\x12\x17\n" +
	"\x13RPKI_STATUS_INVALID\x10\x02\x12\x19\n" +
	"\x15RPKI_STATUS_NOT_FOUND\x10\x03*\x95\x01\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_TYPE_BY_LOCATION\x10\x01\x12\x15\n" +
	"\x11ALERT_TYPE_BY_ASN\x10\x02\x12\x19\n" +
	"\x15ALERT_TYPE_BY_COUNTRY\x10\x03\x12\x1e\n" +
	"\x1aALERT_TYPE_BY_ORGANIZATION\x10\x042\xba\x05\n" +
	"\x0eLiveMapService\x12\\\n" +
	"\x0fSubscribeEvents\x12\".livemap.v1.SubscribeEventsRequest\x1a#.livemap.v1.SubscribeEventsResponse0\x01\x12K\n" +
	"\n" +
	"GetSummary\x12\x1d.livemap.v1.GetSummaryRequest\x1a\x1e.livemap.v1.GetSummaryResponse\x12q\n" +
	"\x16StreamStateTransitions\x12).livemap.v1.StreamStateTransitionsRequest\x1a*.livemap.v1.StreamStateTransitionsResponse0\x01\x12S\n" +
	"\fStreamAlerts\x12\x1f.livemap.v1.StreamAlertsRequest\x1a .livemap.v1.StreamAlertsResponse0\x01\x12n\n" +
	"\x15StreamPrefixSnapshots\x12(.livemap.v1.StreamPrefixSnapshotsRequest\x1a).livemap.v1.StreamPrefixSnapshotsResponse0\x01\x12Z\n" +
	"\x0fGetRecentAlerts\x12\".livemap.v1.GetRecentAlertsRequest\x1a#.livemap.v1.GetRecentAlertsResponse\x12i\n" +
	"\x14GetFlappiestNetworks\x12'.livemap.v1.GetFlappiestNetworksRequest\x1a(.livemap.v1.GetFlappiestNetworksResponseB\x98\x01\n" +
	"\x0ecom.livemap.v1B\fLivemapProtoP\x01Z/github.com/sudorandom/bgp-stream/pkg/livemap/v1\xa2\x02\x03LXX\xaa\x02\n" +
	"Livemap.V1\xca\x02\n" +
	"Livemap\\V1\xe2\x02\x16Livemap\\V1\\GPBMetadata\xea\x02\vLivemap::V1b\x06proto3"

var (
	file_livemap_v1_livemap_proto_rawDescOnce sync.Once
	file_livemap_v1_livemap_proto_rawDescData []byte
)

func file_livemap_v1_livemap_proto_rawDescGZIP() []byte {
	file_livemap_v1_livemap_proto_rawDescOnce.Do(func() {
		file_livemap_v1_livemap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livemap_v1_livemap_proto_rawDesc), len(file_livemap_v1_livemap_proto_rawDesc)))
	})
	return file_livemap_v1_livemap_proto_rawDescData
}

var file_livemap_v1_livemap_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_livemap_v1_livemap_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_livemap_v1_livemap_proto_goTypes = []any{
	(Classification)(0),                    // 0: livemap.v1.Classification
	(RPKIStatus)(0),                        // 1: livemap.v1.RPKIStatus
	(AlertType)(0),                         // 2: livemap.v1.AlertType
	(*GeoData)(nil),                        // 3: livemap.v1.GeoData
	(*AggregatedEvent)(nil),                // 4: livemap.v1.AggregatedEvent
	(*SubscribeEventsResponse)(nil),        // 5: livemap.v1.SubscribeEventsResponse
	(*SubscribeEventsRequest)(nil),         // 6: livemap.v1.SubscribeEventsRequest
	(*GetSummaryRequest)(nil),              // 7: livemap.v1.GetSummaryRequest
	(*ClassificationCount)(nil),            // 8: livemap.v1.ClassificationCount
	(*CompositionEntry)(nil),               // 9: livemap.v1.CompositionEntry
	(*GetSummaryResponse)(nil),             // 10: livemap.v1.GetSummaryResponse
	(*FlappiestNetworkStats)(nil),          // 11: livemap.v1.FlappiestNetworkStats
	(*LeakDetail)(nil),                     // 12: livemap.v1.LeakDetail
	(*StateTransition)(nil),                // 13: livemap.v1.StateTransition
	(*AlertLocation)(nil),                  // 14: livemap.v1.AlertLocation
	(*Alert)(nil),                          // 15: livemap.v1.Alert
	(*StreamAlertsRequest)(nil),            // 16: livemap.v1.StreamAlertsRequest
	(*StreamAlertsResponse)(nil),           // 17: livemap.v1.StreamAlertsResponse
	(*GetRecentAlertsRequest)(nil),         // 18: livemap.v1.GetRecentAlertsRequest
	(*GetRecentAlertsResponse)(nil),        // 19: livemap.v1.GetRecentAlertsResponse
	(*StreamStateTransitionsRequest)(nil),  // 20: livemap.v1.StreamStateTransitionsRequest
	(*StreamStateTransitionsResponse)(nil), // 21: livemap.v1.StreamStateTransitionsResponse
	(*GetFlappiestNetworksRequest)(nil),    // 22: livemap.v1.GetFlappiestNetworksRequest
	(*GetFlappiestNetworksResponse)(nil),   // 23: livemap.v1.GetFlappiestNetworksResponse
	(*StreamPrefixSnapshotsRequest)(nil),   // 24: livemap.v1.StreamPrefixSnapshotsRequest
	(*StreamPrefixSnapshotsResponse)(nil),  // 25: livemap.v1.StreamPrefixSnapshotsResponse
	(*PrefixSnapshot)(nil),                 // 26: livemap.v1.PrefixSnapshot
}
var file_livemap_v1_livemap_proto_depIdxs = []int32{
	3,  // 0: livemap.v1.AggregatedEvent.geo:type_name -> livemap.v1.GeoData
	0,  // 1: livemap.v1.AggregatedEvent.classification:type_name -> livemap.v1.Classification
	4,  // 2: livemap.v1.SubscribeEventsResponse.events:type_name -> livemap.v1.AggregatedEvent
	0,  // 3: livemap.v1.ClassificationCount.classification:type_name -> livemap.v1.Classification
	8,  // 4: livemap.v1.GetSummaryResponse.classification_counts:type_name -> livemap.v1.ClassificationCount
	9,  // 5: livemap.v1.GetSummaryResponse.event_composition:type_name -> livemap.v1.CompositionEntry
	1,  // 6: livemap.v1.GetSummaryResponse.last_rpki_status:type_name -> livemap.v1.RPKIStatus
	11, // 7: livemap.v1.GetSummaryResponse.flappiest_network_stats:type_name -> livemap.v1.FlappiestNetworkStats
	1,  // 8: livemap.v1.LeakDetail.leaker_rpki_status:type_name -> livemap.v1.RPKIStatus
	1,  // 9: livemap.v1.LeakDetail.victim_rpki_status:type_name -> livemap.v1.RPKIStatus
	3,  // 10: livemap.v1.StateTransition.geo:type_name -> livemap.v1.GeoData
	0,  // 11: livemap.v1.StateTransition.new_state:type_name -> livemap.v1.Classification
	0,  // 12: livemap.v1.StateTransition.old_state:type_name -> livemap.v1.Classification
	12, // 13: livemap.v1.StateTransition.leak_detail:type_name -> livemap.v1.LeakDetail
	1,  // 14: livemap.v1.StateTransition.rpki_status:type_name -> livemap.v1.RPKIStatus
	2,  // 15: livemap.v1.Alert.alert_type:type_name -> livemap.v1.AlertType
	14, // 16: livemap.v1.Alert.location:type_name -> livemap.v1.AlertLocation
	0,  // 17: livemap.v1.Alert.classification:type_name -> livemap.v1.Classification
	13, // 18: livemap.v1.Alert.sample_events:type_name -> livemap.v1.StateTransition
	15, // 19: livemap.v1.StreamAlertsResponse.alert:type_name -> livemap.v1.Alert
	15, // 20: livemap.v1.GetRecentAlertsResponse.alerts:type_name -> livemap.v1.Alert
	0,  // 21: livemap.v1.StreamStateTransitionsRequest.target_states:type_name -> livemap.v1.Classification
	13, // 22: livemap.v1.StreamStateTransitionsResponse.transition:type_name -> livemap.v1.StateTransition
	11, // 23: livemap.v1.GetFlappiestNetworksResponse.flappiest_networks:type_name -> livemap.v1.FlappiestNetworkStats
	26, // 24: livemap.v1.StreamPrefixSnapshotsResponse.snapshots:type_name -> livemap.v1.PrefixSnapshot
	0,  // 25: livemap.v1.PrefixSnapshot.classification:type_name -> livemap.v1.Classification
	6,  // 26: livemap.v1.LiveMapService.SubscribeEvents:input_type -> livemap.v1.SubscribeEventsRequest
	7,  // 27: livemap.v1.LiveMapService.GetSummary:input_type -> livemap.v1.GetSummaryRequest
	20, // 28: livemap.v1.LiveMapService.StreamStateTransitions:input_type -> livemap.v1.StreamStateTransitionsRequest
	16, // 29: livemap.v1.LiveMapService.StreamAlerts:input_type -> livemap.v1.StreamAlertsRequest
	24, // 30: livemap.v1.LiveMapService.StreamPrefixSnapshots:input_type -> livemap.v1.StreamPrefixSnapshotsRequest
	18, // 31: livemap.v1.LiveMapService.GetRecentAlerts:input_type -> livemap.v1.GetRecentAlertsRequest
	22, // 32: livemap.v1.LiveMapService.GetFlappiestNetworks:input_type -> livemap.v1.GetFlappiestNetworksRequest
	5,  // 33: livemap.v1.LiveMapService.SubscribeEvents:output_type -> livemap.v1.SubscribeEventsResponse
	10, // 34: livemap.v1.LiveMapService.GetSummary:output_type -> livemap.v1.GetSummaryResponse
	21, // 35: livemap.v1.LiveMapService.StreamStateTransitions:output_type -> livemap.v1.StreamStateTransitionsResponse
	17, // 36: livemap.v1.LiveMapService.StreamAlerts:output_type -> livemap.v1.StreamAlertsResponse
	25, // 37: livemap.v1.LiveMapService.StreamPrefixSnapshots:output_type -> livemap.v1.StreamPrefixSnapshotsResponse
	19, // 38: livemap.v1.LiveMapService.GetRecentAlerts:output_type -> livemap.v1.GetRecentAlertsResponse
	23, // 39: livemap.v1.LiveMapService.GetFlappiestNetworks:output_type -> livemap.v1.GetFlappiestNetworksResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_livemap_v1_livemap_proto_init() }
func file_livemap_v1_livemap_proto_init() {
	if File_livemap_v1_livemap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livemap_v1_livemap_proto_rawDesc), len(file_livemap_v1_livemap_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livemap_v1_livemap_proto_goTypes,
		DependencyIndexes: file_livemap_v1_livemap_proto_depIdxs,
		EnumInfos:         file_livemap_v1_livemap_proto_enumTypes,
		MessageInfos:      file_livemap_v1_livemap_proto_msgTypes,
	}.Build()
	File_livemap_v1_livemap_proto = out.File
	file_livemap_v1_livemap_proto_goTypes = nil
	file_livemap_v1_livemap_proto_depIdxs = nil
}
