// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: livemap/v1/livemap.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiveMapService_SubscribeEvents_FullMethodName        = "/livemap.v1.LiveMapService/SubscribeEvents"
	LiveMapService_GetSummary_FullMethodName             = "/livemap.v1.LiveMapService/GetSummary"
	LiveMapService_StreamStateTransitions_FullMethodName = "/livemap.v1.LiveMapService/StreamStateTransitions"
	LiveMapService_StreamAlerts_FullMethodName           = "/livemap.v1.LiveMapService/StreamAlerts"
	LiveMapService_StreamPrefixSnapshots_FullMethodName  = "/livemap.v1.LiveMapService/StreamPrefixSnapshots"
	LiveMapService_GetRecentAlerts_FullMethodName        = "/livemap.v1.LiveMapService/GetRecentAlerts"
	LiveMapService_GetFlappiestNetworks_FullMethodName   = "/livemap.v1.LiveMapService/GetFlappiestNetworks"
)

// LiveMapServiceClient is the client API for LiveMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LiveMapService provides BGP visualization data.
type LiveMapServiceClient interface {
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEventsResponse], error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
	StreamStateTransitions(ctx context.Context, in *StreamStateTransitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamStateTransitionsResponse], error)
	StreamAlerts(ctx context.Context, in *StreamAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAlertsResponse], error)
	StreamPrefixSnapshots(ctx context.Context, in *StreamPrefixSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPrefixSnapshotsResponse], error)
	GetRecentAlerts(ctx context.Context, in *GetRecentAlertsRequest, opts ...grpc.CallOption) (*GetRecentAlertsResponse, error)
	GetFlappiestNetworks(ctx context.Context, in *GetFlappiestNetworksRequest, opts ...grpc.CallOption) (*GetFlappiestNetworksResponse, error)
}

type liveMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveMapServiceClient(cc grpc.ClientConnInterface) LiveMapServiceClient {
	return &liveMapServiceClient{cc}
}

func (c *liveMapServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMapService_ServiceDesc.Streams[0], LiveMapService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, SubscribeEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_SubscribeEventsClient = grpc.ServerStreamingClient[SubscribeEventsResponse]

func (c *liveMapServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, LiveMapService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveMapServiceClient) StreamStateTransitions(ctx context.Context, in *StreamStateTransitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamStateTransitionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMapService_ServiceDesc.Streams[1], LiveMapService_StreamStateTransitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStateTransitionsRequest, StreamStateTransitionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamStateTransitionsClient = grpc.ServerStreamingClient[StreamStateTransitionsResponse]

func (c *liveMapServiceClient) StreamAlerts(ctx context.Context, in *StreamAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAlertsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMapService_ServiceDesc.Streams[2], LiveMapService_StreamAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAlertsRequest, StreamAlertsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamAlertsClient = grpc.ServerStreamingClient[StreamAlertsResponse]

func (c *liveMapServiceClient) StreamPrefixSnapshots(ctx context.Context, in *StreamPrefixSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPrefixSnapshotsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMapService_ServiceDesc.Streams[3], LiveMapService_StreamPrefixSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPrefixSnapshotsRequest, StreamPrefixSnapshotsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamPrefixSnapshotsClient = grpc.ServerStreamingClient[StreamPrefixSnapshotsResponse]

func (c *liveMapServiceClient) GetRecentAlerts(ctx context.Context, in *GetRecentAlertsRequest, opts ...grpc.CallOption) (*GetRecentAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentAlertsResponse)
	err := c.cc.Invoke(ctx, LiveMapService_GetRecentAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveMapServiceClient) GetFlappiestNetworks(ctx context.Context, in *GetFlappiestNetworksRequest, opts ...grpc.CallOption) (*GetFlappiestNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlappiestNetworksResponse)
	err := c.cc.Invoke(ctx, LiveMapService_GetFlappiestNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveMapServiceServer is the server API for LiveMapService service.
// All implementations must embed UnimplementedLiveMapServiceServer
// for forward compatibility.
//
// LiveMapService provides BGP visualization data.
type LiveMapServiceServer interface {
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SubscribeEventsResponse]) error
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	StreamStateTransitions(*StreamStateTransitionsRequest, grpc.ServerStreamingServer[StreamStateTransitionsResponse]) error
	StreamAlerts(*StreamAlertsRequest, grpc.ServerStreamingServer[StreamAlertsResponse]) error
	StreamPrefixSnapshots(*StreamPrefixSnapshotsRequest, grpc.ServerStreamingServer[StreamPrefixSnapshotsResponse]) error
	GetRecentAlerts(context.Context, *GetRecentAlertsRequest) (*GetRecentAlertsResponse, error)
	GetFlappiestNetworks(context.Context, *GetFlappiestNetworksRequest) (*GetFlappiestNetworksResponse, error)
	mustEmbedUnimplementedLiveMapServiceServer()
}

// UnimplementedLiveMapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveMapServiceServer struct{}

func (UnimplementedLiveMapServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SubscribeEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedLiveMapServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedLiveMapServiceServer) StreamStateTransitions(*StreamStateTransitionsRequest, grpc.ServerStreamingServer[StreamStateTransitionsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStateTransitions not implemented")
}
func (UnimplementedLiveMapServiceServer) StreamAlerts(*StreamAlertsRequest, grpc.ServerStreamingServer[StreamAlertsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAlerts not implemented")
}
func (UnimplementedLiveMapServiceServer) StreamPrefixSnapshots(*StreamPrefixSnapshotsRequest, grpc.ServerStreamingServer[StreamPrefixSnapshotsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamPrefixSnapshots not implemented")
}
func (UnimplementedLiveMapServiceServer) GetRecentAlerts(context.Context, *GetRecentAlertsRequest) (*GetRecentAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentAlerts not implemented")
}
func (UnimplementedLiveMapServiceServer) GetFlappiestNetworks(context.Context, *GetFlappiestNetworksRequest) (*GetFlappiestNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlappiestNetworks not implemented")
}
func (UnimplementedLiveMapServiceServer) mustEmbedUnimplementedLiveMapServiceServer() {}
func (UnimplementedLiveMapServiceServer) testEmbeddedByValue()                        {}

// UnsafeLiveMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveMapServiceServer will
// result in compilation errors.
type UnsafeLiveMapServiceServer interface {
	mustEmbedUnimplementedLiveMapServiceServer()
}

func RegisterLiveMapServiceServer(s grpc.ServiceRegistrar, srv LiveMapServiceServer) {
	// If the following call panics, it indicates UnimplementedLiveMapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiveMapService_ServiceDesc, srv)
}

func _LiveMapService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, SubscribeEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_SubscribeEventsServer = grpc.ServerStreamingServer[SubscribeEventsResponse]

func _LiveMapService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveMapServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveMapService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveMapServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveMapService_StreamStateTransitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStateTransitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServiceServer).StreamStateTransitions(m, &grpc.GenericServerStream[StreamStateTransitionsRequest, StreamStateTransitionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamStateTransitionsServer = grpc.ServerStreamingServer[StreamStateTransitionsResponse]

func _LiveMapService_StreamAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAlertsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServiceServer).StreamAlerts(m, &grpc.GenericServerStream[StreamAlertsRequest, StreamAlertsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamAlertsServer = grpc.ServerStreamingServer[StreamAlertsResponse]

func _LiveMapService_StreamPrefixSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPrefixSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServiceServer).StreamPrefixSnapshots(m, &grpc.GenericServerStream[StreamPrefixSnapshotsRequest, StreamPrefixSnapshotsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMapService_StreamPrefixSnapshotsServer = grpc.ServerStreamingServer[StreamPrefixSnapshotsResponse]

func _LiveMapService_GetRecentAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveMapServiceServer).GetRecentAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveMapService_GetRecentAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveMapServiceServer).GetRecentAlerts(ctx, req.(*GetRecentAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveMapService_GetFlappiestNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlappiestNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveMapServiceServer).GetFlappiestNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveMapService_GetFlappiestNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveMapServiceServer).GetFlappiestNetworks(ctx, req.(*GetFlappiestNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiveMapService_ServiceDesc is the grpc.ServiceDesc for LiveMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livemap.v1.LiveMapService",
	HandlerType: (*LiveMapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _LiveMapService_GetSummary_Handler,
		},
		{
			MethodName: "GetRecentAlerts",
			Handler:    _LiveMapService_GetRecentAlerts_Handler,
		},
		{
			MethodName: "GetFlappiestNetworks",
			Handler:    _LiveMapService_GetFlappiestNetworks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _LiveMapService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStateTransitions",
			Handler:       _LiveMapService_StreamStateTransitions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAlerts",
			Handler:       _LiveMapService_StreamAlerts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPrefixSnapshots",
			Handler:       _LiveMapService_StreamPrefixSnapshots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "livemap/v1/livemap.proto",
}
