// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: historical/v1/historical.proto

package v1

import (
	_ "github.com/sudorandom/bgp-stream/pkg/livemap/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyAsnArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Prefixes      []*PrefixHistory       `protobuf:"bytes,4,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyAsnArchive) Reset() {
	*x = DailyAsnArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyAsnArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyAsnArchive) ProtoMessage() {}

func (x *DailyAsnArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyAsnArchive.ProtoReflect.Descriptor instead.
func (*DailyAsnArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{0}
}

func (x *DailyAsnArchive) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *DailyAsnArchive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DailyAsnArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DailyAsnArchive) GetPrefixes() []*PrefixHistory {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type PrefixHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Events        []*Transition          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixHistory) Reset() {
	*x = PrefixHistory{}
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixHistory) ProtoMessage() {}

func (x *PrefixHistory) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixHistory.ProtoReflect.Descriptor instead.
func (*PrefixHistory) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{1}
}

func (x *PrefixHistory) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixHistory) GetEvents() []*Transition {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldState      int32                  `protobuf:"varint,1,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState      int32                  `protobuf:"varint,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{2}
}

func (x *Transition) GetOldState() int32 {
	if x != nil {
		return x.OldState
	}
	return 0
}

func (x *Transition) GetNewState() int32 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *Transition) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type DaySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Date             int64                  `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"` // Unix timestamp for start of day
	TotalTransitions uint32                 `protobuf:"varint,2,opt,name=total_transitions,json=totalTransitions,proto3" json:"total_transitions,omitempty"`
	UniqueAsns       uint32                 `protobuf:"varint,3,opt,name=unique_asns,json=uniqueAsns,proto3" json:"unique_asns,omitempty"`
	UniquePrefixes   uint32                 `protobuf:"varint,4,opt,name=unique_prefixes,json=uniquePrefixes,proto3" json:"unique_prefixes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DaySummary) Reset() {
	*x = DaySummary{}
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySummary) ProtoMessage() {}

func (x *DaySummary) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySummary.ProtoReflect.Descriptor instead.
func (*DaySummary) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{3}
}

func (x *DaySummary) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *DaySummary) GetTotalTransitions() uint32 {
	if x != nil {
		return x.TotalTransitions
	}
	return 0
}

func (x *DaySummary) GetUniqueAsns() uint32 {
	if x != nil {
		return x.UniqueAsns
	}
	return 0
}

func (x *DaySummary) GetUniquePrefixes() uint32 {
	if x != nil {
		return x.UniquePrefixes
	}
	return 0
}

type OrgArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Asns          []uint32               `protobuf:"varint,2,rep,packed,name=asns,proto3" json:"asns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgArchive) Reset() {
	*x = OrgArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgArchive) ProtoMessage() {}

func (x *OrgArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgArchive.ProtoReflect.Descriptor instead.
func (*OrgArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{4}
}

func (x *OrgArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *OrgArchive) GetAsns() []uint32 {
	if x != nil {
		return x.Asns
	}
	return nil
}

var File_historical_v1_historical_proto protoreflect.FileDescriptor

const file_historical_v1_historical_proto_rawDesc = "" +
	"\n" +
	"\x1ehistorical/v1/historical.proto\x12\rhistorical.v1\x1a\x18livemap/v1/livemap.proto\"\x83\x01\n" +
	"\x0fDailyAsnArchive\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x128\n" +
	"\bprefixes\x18\x04 \x03(\v2\x1c.historical.v1.PrefixHistoryR\bprefixes\"Z\n" +
	"\rPrefixHistory\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x121\n" +
	"\x06events\x18\x02 \x03(\v2\x19.historical.v1.TransitionR\x06events\"V\n" +
	"\n" +
	"Transition\x12\x1b\n" +
	"\told_state\x18\x01 \x01(\x05R\boldState\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\x05R\bnewState\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"\x97\x01\n" +
	"\n" +
	"DaySummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x03R\x04date\x12+\n" +
	"\x11total_transitions\x18\x02 \x01(\rR\x10totalTransitions\x12\x1f\n" +
	"\vunique_asns\x18\x03 \x01(\rR\n" +
	"uniqueAsns\x12'\n" +
	"\x0funique_prefixes\x18\x04 \x01(\rR\x0euniquePrefixes\"2\n" +
	"\n" +
	"OrgArchive\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04asns\x18\x02 \x03(\rR\x04asnsB\xad\x01\n" +
	"\x11com.historical.v1B\x0fHistoricalProtoP\x01Z2github.com/sudorandom/bgp-stream/pkg/historical/v1\xa2\x02\x03HXX\xaa\x02\rHistorical.V1\xca\x02\rHistorical\\V1\xe2\x02\x19Historical\\V1\\GPBMetadata\xea\x02\x0eHistorical::V1b\x06proto3"

var (
	file_historical_v1_historical_proto_rawDescOnce sync.Once
	file_historical_v1_historical_proto_rawDescData []byte
)

func file_historical_v1_historical_proto_rawDescGZIP() []byte {
	file_historical_v1_historical_proto_rawDescOnce.Do(func() {
		file_historical_v1_historical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)))
	})
	return file_historical_v1_historical_proto_rawDescData
}

var file_historical_v1_historical_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_historical_v1_historical_proto_goTypes = []any{
	(*DailyAsnArchive)(nil), // 0: historical.v1.DailyAsnArchive
	(*PrefixHistory)(nil),   // 1: historical.v1.PrefixHistory
	(*Transition)(nil),      // 2: historical.v1.Transition
	(*DaySummary)(nil),      // 3: historical.v1.DaySummary
	(*OrgArchive)(nil),      // 4: historical.v1.OrgArchive
}
var file_historical_v1_historical_proto_depIdxs = []int32{
	1, // 0: historical.v1.DailyAsnArchive.prefixes:type_name -> historical.v1.PrefixHistory
	2, // 1: historical.v1.PrefixHistory.events:type_name -> historical.v1.Transition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_historical_v1_historical_proto_init() }
func file_historical_v1_historical_proto_init() {
	if File_historical_v1_historical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_historical_v1_historical_proto_goTypes,
		DependencyIndexes: file_historical_v1_historical_proto_depIdxs,
		MessageInfos:      file_historical_v1_historical_proto_msgTypes,
	}.Build()
	File_historical_v1_historical_proto = out.File
	file_historical_v1_historical_proto_goTypes = nil
	file_historical_v1_historical_proto_depIdxs = nil
}
