[tools]
rust = "latest"
buf = "latest"
just = "latest"
cmake = "latest"
go = "1.26.1"
golangci-lint = "latest"
node = "latest"
pnpm = "latest"
wrangler = "latest"
"npm:@bufbuild/protoc-gen-es" = "latest"
"npm:@bufbuild/buf" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
goreleaser = "2.14.1"
"github:sudorandom/fauxrpc" = "latest"
