print("Ah! It does set `ce.CachedNetLabel` and `ce.CachedNetVal` in `cacheLeakStrings`.")
print("But wait! If `ce.LeakType == bgp.LeakUnknown` (which happens if `leak_type` is 0), NO details are drawn for Route Leaks!")
print("```go\ncase bgp.NameRouteLeak, bgp.NameMinorRouteLeak:\n    if ce.LeakType != bgp.LeakUnknown {\n        // Leaker\n        ...\n        // Networks line\n        nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, ...)\n    }\n```")
print("If the user saw a ROUTE LEAK with NO details, it MUST be because `ce.LeakType == bgp.LeakUnknown`.")
print("Why would `ce.LeakType` be `bgp.LeakUnknown` for a Route Leak?!")
print("Because `trans.LeakDetail` was `nil`?")
print("Wait! `find_critical_anomaly` ALWAYS returns `Some(ld)` for Route Leaks!")
print("Is there ANOTHER place where Route Leaks are created?")
print("Yes! What if `state.classified_type` was already `ClassificationType::RouteLeak`, and it transitions to a NEW `ClassificationType::RouteLeak`? No, it only sends transitions if the state CHANGES.")
print("What if the OLD state was something else, and it transitions to Route Leak?")
print("Then `find_critical_anomaly` must have returned `ClassificationType::RouteLeak`!")
print("Wait, look at `find_critical_anomaly` again.")
