print("BINGO!!!")
print("`livemap.proto` has:")
print("`CLASSIFICATION_UNSPECIFIED = 0;`")
print("`CLASSIFICATION_BOGON = 1;`")
print("`CLASSIFICATION_HIJACK = 2;`")
print("`CLASSIFICATION_ROUTE_LEAK = 3;`")
print("`CLASSIFICATION_OUTAGE = 4;`")
print("`CLASSIFICATION_DDOS_MITIGATION = 5;`")
print("`CLASSIFICATION_FLAP = 6;`")
print("`CLASSIFICATION_PATH_HUNTING = 8;`")
print("`CLASSIFICATION_DISCOVERY = 9;`")
print("`CLASSIFICATION_MINOR_ROUTE_LEAK = 10;`")

print("But `pkg/bgp/types.go` has:")
print("```go\nconst (\n	ClassificationNone ClassificationType = iota\n	ClassificationBogon\n	ClassificationHijack\n	ClassificationRouteLeak\n	ClassificationMinorRouteLeak // wait! 4!!!\n	ClassificationOutage // 5!!!\n	ClassificationDDoSMitigation // 6!!!\n	ClassificationFlap // 7!!!\n	ClassificationPathHunting // 8!!!\n	ClassificationDiscovery // 9!!!\n)\n```")
print("If the rust backend sends `CLASSIFICATION_ROUTE_LEAK` (3), Go reads 3 (`ClassificationRouteLeak`). OK!")
print("If the rust backend sends `CLASSIFICATION_MINOR_ROUTE_LEAK` (10), `ct = bgp.ClassificationType(10)`. Wait, 10 isn't even defined in the Go `const` block! Wait, `ClassificationDiscovery` is 9! If `ct` is 10, what does `String()` return?")
print("```go\ndefault:\n    return \"Discovery\"\n```")
print("If Rust sends `CLASSIFICATION_HIJACK` (2), Go reads 2 (`ClassificationHijack`). OK!")
print("If Rust sends `CLASSIFICATION_OUTAGE` (4), Go reads 4! But in Go, 4 is `ClassificationMinorRouteLeak`!!!")
print("So `String()` returns `NameRouteLeak`!")
print("Wait, `String()`:")
print("```go\n    case ClassificationRouteLeak, ClassificationMinorRouteLeak:\n        return NameRouteLeak\n```")
print("Ah!! So an OUTAGE (4) comes in, Go treats it as `ClassificationMinorRouteLeak` (4), and displays it as `ROUTE LEAK`!!!")
print("And because it's a Route Leak, `status.go` expects `LeakType` and `LeakDetail`.")
print("But it was an OUTAGE, so it HAS NO LEAK DETAIL!")
print("So `LeakType` is `0` (`bgp.LeakUnknown`), so NO DETAILS ARE DRAWN!!!")
print("And the user sees a \"ROUTE LEAK\" (which is actually an OUTAGE) with NO DETAILS, EXCEPT THE ASN AND PREFIX!!!")
print("Wait! Outage DOES NOT HAVE LEAK DETAIL!")

print("If Rust sends `CLASSIFICATION_FLAP` (6), Go reads 6 (`ClassificationDDoSMitigation`)!")
print("`ct.String()` returns `NameDDoSMitigation`!")
print("So the user sees \"DDOS MITIGATION\" instead of Flap!!!")
print("Wait, if `ClassificationFlap` is 7 in Go, but it's 6 in protobuf.")
print("If Rust sends Flap (6), Go treats it as DDoS Mitigation.")
print("Does the UI drop DDoS Mitigation? No.")
print("Wait! Let's look at `RecordStateTransition`:")
print("```go\nif ct != bgp.ClassificationOutage && ct != bgp.ClassificationRouteLeak && ct != bgp.ClassificationMinorRouteLeak && ct != bgp.ClassificationHijack && ct != bgp.ClassificationFlap {\n```")
print("Wait! `ct` is 6 (which is `ClassificationDDoSMitigation` in Go).")
print("Is 6 in the allowed list?")
print("`bgp.ClassificationOutage` is 5.")
print("`bgp.ClassificationRouteLeak` is 3.")
print("`bgp.ClassificationMinorRouteLeak` is 4.")
print("`bgp.ClassificationHijack` is 2.")
print("`bgp.ClassificationFlap` is 7.")
print("Since `ct` is 6, it IS NOT in the allowed list! So it is DROPPED!!!")
print("This is why Flaps are detecting ZERO events!!!")

print("Wait... does `ClassificationType` in `pkg/bgp/types.go` even need to exist? Why not use the auto-generated protobuf enum `livemap.Classification`?!")
print("Because `pkg/bgp` might be used for other things?")
print("Regardless, we MUST fix the constants in `pkg/bgp/types.go` to match the protobuf enum!")
