print("Wait, `bgp.ClassificationType` is defined as:")
print("```go\nconst (\n    ClassificationNone ClassificationType = iota\n    ClassificationBogon\n    ClassificationHijack\n    ClassificationRouteLeak\n    ClassificationMinorRouteLeak\n    ClassificationOutage\n    ...\n```")
print("But wait! `trans.NewState` is an `enum` from protobuf `livemap.Classification`.")
print("In `livemap.proto`:")
print("```protobuf\nenum Classification {\n  CLASSIFICATION_UNSPECIFIED = 0;\n  CLASSIFICATION_BOGON = 1;\n  CLASSIFICATION_HIJACK = 2;\n  CLASSIFICATION_ROUTE_LEAK = 3;\n  CLASSIFICATION_OUTAGE = 4;\n  CLASSIFICATION_DDOS_MITIGATION = 5;\n  CLASSIFICATION_FLAP = 6;\n  CLASSIFICATION_PATH_HUNTING = 8;\n  CLASSIFICATION_DISCOVERY = 9;\n  CLASSIFICATION_MINOR_ROUTE_LEAK = 10;\n}\n```")
print("Wait! `bgp.ClassificationType` uses `iota`!")
print("```go\ntype ClassificationType int\nconst (\n    ClassificationNone ClassificationType = iota // 0\n    ClassificationBogon // 1\n    ClassificationHijack // 2\n    ClassificationRouteLeak // 3\n    ClassificationMinorRouteLeak // 4\n    ClassificationOutage // 5\n    ClassificationDDoSMitigation // 6\n    ClassificationFlap // 7\n    ClassificationPathHunting // 8\n    ClassificationDiscovery // 9\n)\n```")
print("OH MY GOD!!!")
print("If `trans.NewState` is `CLASSIFICATION_HIJACK` (2), `bgp.ClassificationType(2)` is `ClassificationHijack`.")
print("If `trans.NewState` is `CLASSIFICATION_ROUTE_LEAK` (3), `bgp.ClassificationType(3)` is `ClassificationRouteLeak`.")
print("If `trans.NewState` is `CLASSIFICATION_OUTAGE` (4), `bgp.ClassificationType(4)` is `ClassificationMinorRouteLeak` in `bgp.ClassificationType`!!!!")
print("If `trans.NewState` is `CLASSIFICATION_DDOS_MITIGATION` (5), `bgp.ClassificationType(5)` is `ClassificationOutage`!!!!")
print("If `trans.NewState` is `CLASSIFICATION_FLAP` (6), `bgp.ClassificationType(6)` is `ClassificationDDoSMitigation`!!!!")
print("If `trans.NewState` is `CLASSIFICATION_PATH_HUNTING` (8), `bgp.ClassificationType(8)` is `ClassificationPathHunting` (wait, no! 8 is `ClassificationPathHunting` because `ClassificationFlap` is 7?!)")
print("Let's look at `pkg/bgp/types.go` definitions exactly.")
