print("If the user says 'The prefix isn't displayed':")
print("Look at `ce.CachedFirstLine = \"\"` in `cacheOutageStrings`!")
print("Wait... does `cacheHijackDDoSStrings` clear `ce.CachedFirstLine`?")
print("No.")
print("Does `status.go` draw `ce.CachedFirstLine`? Yes, using `drawWrappedText`.")
print("Wait, does `e.drawLabeledLine` use `label` correctly? Let's check `drawLabeledLine`.")
print("If the user is talking about a ROUTE LEAK:")
print("Maybe I should make sure Route Leak events are correctly drawn in `status.go`?!")
print("Wait... in `status.go`:")
print("```go\n	case bgp.NameRouteLeak, bgp.NameMinorRouteLeak:\n		if ce.LeakType != bgp.LeakUnknown {\n			// Leaker\n			nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedLeakerLabel, ce.LeakerRPKI, ce.CachedLeakerVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n			// Impacted\n			nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedVictimLabel, ce.VictimRPKI, ce.CachedVictimVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n			// Networks line\n			nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n		}\n```")
print("If `ce.LeakType` IS `bgp.LeakUnknown`, then NO details are drawn!! Just the ASN and prefix.")
print("Could `ce.LeakType` be `bgp.LeakUnknown`? If the JSON lacks `leakType`, it means `trans.LeakDetail.LeakType` is `0` (which is `LeakType::None`).")
print("Wait! `trans.LeakDetail.LeakType` CAN be `0`?!")
print("If the event is `CLASSIFICATION_ROUTE_LEAK`, how can `leakType` be 0?")
print("Wait... `detect_route_leak` only returns `LeakType::ValleyFreeViolation` (7) or `Hairpin` (2).")
print("BUT wait... if `oldState` is `ROUTE_LEAK` and `newState` is `HIJACK`, the JSON describes the HIJACK event.")
print("But wait... the user says 'There are still route leaks with no other details other than ASN:' and points to a JSON payload where `newState` is `CLASSIFICATION_HIJACK`.")
print("The user might literally be confused. They saw a Hijack event, but they thought it was a Route Leak event because it says `oldState: CLASSIFICATION_ROUTE_LEAK`.")
print("OR they just copy-pasted a random event, but their complaint applies to Hijacks too!")
print("Wait! For HIJACKS, `trans.LeakDetail.LeakType` IS 0 (`LeakType::None`).")
print("For HIJACKS, in `status.go`:")
print("```go\n	case bgp.NameDDoSMitigation, bgp.NameHijack:\n		// Attacker / Source\n		nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedLeakerLabel, ce.LeakerRPKI, ce.CachedLeakerVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n\n		// Victim / Target\n		nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedVictimLabel, ce.VictimRPKI, ce.CachedVictimVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n```")
print("If it draws this for Hijacks, why did the user say 'The prefix isn't displayed and the names of the networks are not populated.'?")
print("Wait, `ce.CachedNetLabel` is NOT drawn for Hijacks! `e.drawLabeledLine` is passed `ce.CachedImpactStr` and `\"\"` for `value`!")
print("Wait, look at `status.go` for Hijacks:")
print("`nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedImpactStr, \"\", ...)`")
print("Ah! `drawLabeledLine` draws `label` with `labelCol`, and `value` with `valueCol`.")
print("If `value` is `\"\"`, does it draw `label`?")
print("Let's look at `drawLabeledLine`.")
