print("Yes, it draws `label` if `label` is not empty.")
print("Wait, if it draws `label`, it uses `labelCol` (Light gray).")
print("But wait, `ce.CachedImpactStr` has the `pfxStr`.")
print("Is it possible that `ce.ImpactedPrefixes` is EMPTY because we created the event using `updateCriticalEventFromTransition` instead of `createCriticalEventFromTransition`?!")
print("If the user saw the event in the UI, it was likely created by `createCriticalEventFromTransition`.")
print("Let's look at `createCriticalEventFromTransition`:")
print("```go\nfunc (e *Engine) createCriticalEventFromTransition(trans *livemap.StateTransition, c, uiCol color.RGBA, name string) *CriticalEvent {\n    ce := &CriticalEvent{\n        ...\n        ImpactedPrefixes:  make(map[string]struct{}),\n        ActivePrefixes:    make(map[string]struct{}),\n        ActiveIncidentIDs: make(map[string]struct{}),\n    }\n    ce.ImpactedPrefixes[trans.Prefix] = struct{}{}\n    if trans.EndTime == 0 {\n        ce.ActivePrefixes[trans.Prefix] = struct{}{}\n    }\n    ce.ImpactedIPs = utils.GetPrefixSize(trans.Prefix)\n    ...\n    if trans.LeakDetail != nil {\n        ce.LeakerASN = trans.LeakDetail.LeakerAsn\n        ce.LeakerName = trans.LeakDetail.LeakerAsName\n        ...\n        // Map from Rust's LeakType enum to Go's bgp.LeakType\n        switch trans.LeakDetail.LeakType {\n            ...\n        }\n    }\n    e.updateCriticalEventCacheStrs(ce)\n    return ce\n}\n```")
print("Wait! `trans.LeakDetail.LeakerAsName`!")
print("If `trans.LeakDetail.LeakerAsName` is empty in `createCriticalEventFromTransition`, it sets `ce.LeakerName` to empty.")
print("Then `e.updateCriticalEventCacheStrs(ce)` runs.")
print("If `ce.LeakerName` is empty, `ce.CachedLeakerVal = fmt.Sprintf(\"AS%d\", ce.LeakerASN)`.")
print("If the user says 'The prefix isn't displayed and the names of the networks are not populated.'")
print("Wait! In `createCriticalEventFromTransition`:")
print("```go\n    ce := &CriticalEvent{\n        Timestamp:         time.Unix(trans.StartTime, 0),\n        Anom:              name,\n        ASN:               trans.Asn,\n        ASNStr:            fmt.Sprintf(\"AS%d\", trans.Asn),\n        OrgID:             trans.AsName,\n        ...\n    }\n```")
print("`trans.AsName` is `as_name` from the `StateTransition` message.")
print("If `trans.AsName` is empty, `ce.OrgID` is empty.")
print("If `ce.OrgID` is empty, the first line is just `ASxxx`.")
print("If the user complains about `prefix isn't displayed`, look at `ce.CachedFirstLine`:")
print("`ce.CachedFirstLine = fmt.Sprintf(\"%s (%s)\", ce.ASNStr, ce.OrgID)` OR `ce.ASNStr`.")
print("Wait... does `ce.CachedFirstLine` ever display the prefix?!")
print("NO! `ce.CachedFirstLine` is just the ASN and OrgID!")
print("For Hijacks, the prefix is in `ce.CachedImpactStr`: `  Impact(1 IPs): 38.175.96.0/24`.")
print("Wait! Why does the user say 'The prefix isn't displayed' ?")
print("Ah! Look at `cacheLeakStrings`! For Route Leaks, the prefix IS displayed as `  Networks: 38.175.96.0/24`.")
print("Wait, if `ce.LeakType == bgp.LeakUnknown` (which it is for Hijack, because `leak_type` is 0), then `cacheLeakStrings` does NOT display the `Networks` line!")
print("Wait, if the user was looking at a Hijack event, `cacheHijackDDoSStrings` is called. `cacheHijackDDoSStrings` DOES NOT display `ce.CachedNetLabel = \"  Networks: \"`!")
print("No, `cacheHijackDDoSStrings` calls `e.cacheImpactStrings` which populates `ce.CachedImpactStr`, which is then drawn.")
print("Wait... in `drawCriticalEvent`:")
print("```go\n    case bgp.NameDDoSMitigation, bgp.NameHijack:\n        // Attacker / Source\n        nextY = e.drawRPKILine(...)\n        // Victim / Target\n        nextY = e.drawRPKILine(...)\n        // Networks line\n        nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedImpactStr, \"\", e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n```")
print("So the prefix IS drawn for Hijacks!")
print("Why does the user say it's not displayed?!")
print("Wait, if the user thinks it's a ROUTE LEAK because `oldState` was `CLASSIFICATION_ROUTE_LEAK`, and the frontend still thinks it's a ROUTE LEAK because of some bug?!")
print("Wait, if `oldState` was `ROUTE_LEAK` and `newState` is `HIJACK`, does the frontend UPDATE the `Anom` type?")
