print("Ah! The user posted JSON output for a transition:")
print("`\"newState\": \"CLASSIFICATION_HIJACK\", \"oldState\": \"CLASSIFICATION_ROUTE_LEAK\"`")
print("This means the event was previously a ROUTE_LEAK, and is NOW a HIJACK.")
print("But wait! The `leakDetail` they pasted is:")
print("`\"leakDetail\": { \"leakerAsn\": 917, \"victimAsn\": 57695 }`")
print("Why does it NOT have `leakType`?!")
print("In `classifier.rs` for `ClassificationType::Hijack`:")
print("```rust\n                        leak_detail: Some(LeakDetail {\n                            leak_type: LeakType::None,\n                            leaker_asn: ctx.origin_asn,\n                            victim_asn: historical_origin_asn,\n                            leaker_as_name: self.get_as_name(ctx.origin_asn).unwrap_or_default(),\n                            victim_as_name: self.get_as_name(historical_origin_asn).unwrap_or_default(),\n                            leaker_rpki_status: self.rpki_validate(ctx.origin_asn, prefix),\n                            victim_rpki_status: self.rpki_validate(historical_origin_asn, prefix),\n                        }),\n```")
print("If `leak_type` is `LeakType::None` (0), and `protobuf` default values are omitted, then `leakType` will NOT be in the JSON output.")
print("So the event the user is showing is the HIJACK event, NOT the Route Leak event!")
print("The user says: 'There are still route leaks with no other details other than ASN:' and then pastes a HIJACK event.")
print("Wait! The user says 'route leaks' but they paste a HIJACK event.")
print("Ah! The user sees the UI displaying it as a Route Leak? No, the UI displays Hijack.")
print("Wait! Look at `status.go`! For Hijack events:")
print("```go\ncase bgp.NameDDoSMitigation, bgp.NameHijack:\n    // Attacker / Source\n    nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedLeakerLabel, ce.LeakerRPKI, ce.CachedLeakerVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n```")
print("If the user says 'There are still route leaks with no other details other than ASN', maybe they mean BOTH Hijacks and Route Leaks are displaying only ASN because the names are empty?")
print("Wait, the user says 'The prefix isn't displayed and the names of the networks are not populated.'")
print("If the prefix is not displayed, it means `ce.CachedNetLabel` is empty!")
print("Wait! In `cacheHijackDDoSStrings`:")
print("```go\n    // Networks line\n    networks := make([]string, 0, len(ce.ImpactedPrefixes))\n    for p := range ce.ImpactedPrefixes {\n        networks = append(networks, p)\n    }\n    sort.Strings(networks)\n    const maxShow = 2\n    displayNets := networks\n    moreCount := 0\n    if len(networks) > maxShow {\n        displayNets = networks[:maxShow]\n        moreCount = len(networks) - maxShow\n    }\n    ce.CachedNetLabel = \"  Networks: \"\n    netVal := strings.Join(displayNets, \", \")\n    if moreCount > 0 {\n        netVal += fmt.Sprintf(\", (%d more)\", moreCount)\n    }\n    ce.CachedNetVal = netVal\n```")
print("It DOES set `ce.CachedNetLabel`!")
print("BUT wait, earlier I saw `status.go` uses `ce.CachedImpactStr` for Hijacks!")
print("```go\n    case bgp.NameDDoSMitigation, bgp.NameHijack:\n        // Networks line\n        nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedImpactStr, \"\", e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n```")
print("Wait, does `e.cacheImpactStrings(ce)` run? Yes, at the end of `cacheHijackDDoSStrings(ce)`.")
print("Wait... does `e.cacheImpactStrings(ce)` set `ce.CachedImpactStr`?")
print("```go\nfunc (e *Engine) cacheImpactStrings(ce *CriticalEvent) {\n    ...\n    ce.CachedImpactStr = fmt.Sprintf(\"  Impact(%s): %s\", impactStr, pfxStr)\n}\n```")
print("If `pfxStr` is empty, it says `  Impact(0 IPs): `.")
print("Why would `pfxStr` be empty? Because `ce.ImpactedPrefixes` is empty?!")
print("Why would `ce.ImpactedPrefixes` be empty?")
print("In `updateCriticalEventFromTransition`, it sets `ce.ImpactedPrefixes[trans.Prefix] = struct{}{}`.")
print("BUT wait! What if it's the FIRST transition? i.e., `createCriticalEventFromTransition`!")
print("In `createCriticalEventFromTransition`:")
print("```go\nfunc (e *Engine) createCriticalEventFromTransition(trans *livemap.StateTransition, c, uiCol color.RGBA, name string) *CriticalEvent {\n    ce := &CriticalEvent{\n        ...\n        ImpactedPrefixes:  make(map[string]struct{}),\n    }\n    ce.ImpactedPrefixes[trans.Prefix] = struct{}{}\n```")
print("So `ce.ImpactedPrefixes` IS NOT EMPTY! `len(ce.ImpactedPrefixes)` is at least 1.")
print("So `ce.CachedImpactStr` is `  Impact(256 IPs): 38.175.96.0/24`.")
print("So why did the user say 'The prefix isn't displayed'?!")
