print("Wait, `detect_route_leak` returns `ld`. `ld.leak_type` is 7 or 2.")
print("So `leak_detail: Some(ld)` will ALWAYS have `leak_type` 7 or 2.")
print("If `leak_type` is 7 or 2, `trans.LeakDetail.LeakType` will be 7 or 2.")
print("If `trans.LeakDetail.LeakType` is 7 or 2, `ce.LeakType` will be `bgp.LeakValleyFree` or `bgp.LeakHairpin`.")
print("If `ce.LeakType` is NOT `bgp.LeakUnknown`, then it WILL draw the details.")
print("So WHY did the user say 'There are still route leaks with no other details other than ASN'?!")
print("Wait... what if the event the user saw was a Route Leak, but then transitioned to a Hijack.")
print("And because it transitioned to a Hijack, `trans.LeakDetail.LeakType` became 0 (because I set `leak_type: LeakType::None` for Hijacks).")
print("Then `ce.LeakType` became `bgp.LeakUnknown`!")
print("But wait! If it transitioned to Hijack, `ce.Anom` became `bgp.NameHijack`!")
print("For `bgp.NameHijack`, `status.go` draws the attacker and victim regardless of `ce.LeakType`!")
print("Ah! Look at `status.go`:")
print("```go\n	case bgp.NameDDoSMitigation, bgp.NameHijack:\n		// Attacker / Source\n		nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedLeakerLabel, ce.LeakerRPKI, ce.CachedLeakerVal, ...)\n		// Victim / Target\n		nextY = e.drawRPKILine(...)\n		// Networks line\n		nextY = e.drawLabeledLine(..., ce.CachedImpactStr, \"\", ...)\n```")
print("Wait, if it draws them for Hijack, then why does the user say 'no other details other than ASN'?!")
print("Because `ce.CachedLeakerVal` and `ce.CachedVictimVal` were just `AS917` and `AS57695`!")
print("Because `get_as_name` failed to find the names!")
print("AND because `ce.CachedImpactStr` might be drawing `  Impact(1 IPs): 38.175.96.0/24`?")
print("Wait, does `ce.CachedImpactStr` get drawn correctly?")
print("If the JSON has `prefix: 38.175.96.0/24`, then `networks` has 1 element, `pfxStr` is `38.175.96.0/24`.")
print("But the user explicitly said 'The prefix isn't displayed'.")
print("Why would `ce.CachedImpactStr` NOT display the prefix?")
print("Wait, does `ce.CachedImpactStr` get OVERWRITTEN?")
print("Ah! In `status.go` for Route Leak:")
print("```go\n	case bgp.NameRouteLeak, bgp.NameMinorRouteLeak:\n		if ce.LeakType != bgp.LeakUnknown {\n			...\n			// Networks line\n			nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, ...)\n		}\n```")
print("BUT for Route Leak, `ce.CachedNetVal` is drawn!")
print("If the user saw `no other details other than ASN`, they DID NOT SEE the prefix!")
print("Wait, if they didn't see the prefix, it means `ce.CachedNetVal` was empty? Or `ce.LeakType == bgp.LeakUnknown`?!")
