print("Ah! `ce.CachedNetLabel` is set to `\"  Networks: \"` in `cacheHijackDDoSStrings`!")
print("But wait... `ce.CachedNetLabel` is `\"  Networks: \"`.")
print("In `pkg/bgpengine/status.go`:")
print("`nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)`")
print("Why isn't it displayed then?")
print("Because the JSON was `CLASSIFICATION_HIJACK` but maybe something went wrong during testing or reading?")
print("Wait, look at `cacheLeakStrings`:")
print("```go\n    // Networks line\n    networks := make([]string, 0, len(ce.ImpactedPrefixes))\n    for p := range ce.ImpactedPrefixes {\n        networks = append(networks, p)\n    }\n    sort.Strings(networks)\n    const maxShow = 2\n    displayNets := networks\n    moreCount := 0\n    if len(networks) > maxShow {\n        displayNets = networks[:maxShow]\n        moreCount = len(networks) - maxShow\n    }\n    ce.CachedNetLabel = \"  Networks: \"\n    netVal := strings.Join(displayNets, \", \")\n    if moreCount > 0 {\n        netVal += fmt.Sprintf(\", (%d more)\", moreCount)\n    }\n    ce.CachedNetVal = netVal\n```")
print("If the user says 'There are still route leaks with no other details other than ASN: [JSON PAYLOAD] The prefix isn't displayed and the names of the networks are not populated.'")
print("Wait! `trans.Prefix` is in the JSON payload!")
print("But `ce.ImpactedPrefixes` contains `trans.Prefix`!")
print("If `len(ce.ImpactedPrefixes)` is 1, `displayNets` is 1. `netVal` is the prefix. `ce.CachedNetVal` should be populated.")
print("Why does the user say it's not displayed?")
print("Wait, let's check `status.go`!")
