print("Wait, what about the prefix? 'The prefix isn't displayed'")
print("Look at `main.rs`! `prefix: pending.prefix.clone(),`")
print("Wait... `PendingEvent` has `prefix`.")
print("But wait, in `livemap.proto`:")
print("```protobuf\nmessage StateTransition {\n    string incident_id = 1;\n    string prefix = 2;\n```")
print("Wait! `StateTransition` does have `prefix = 2;`")
print("Look at the JSON the user pasted!")
print("```json\n{\n  \"transition\": {\n    \"incidentId\": \"10af4d9f...\",\n    \"prefix\": \"38.175.96.0/24\",\n    \"asn\": 917,\n```")
print("The JSON DOES HAVE `\"prefix\": \"38.175.96.0/24\"`!")
print("If the JSON has `prefix`, why does the user say 'The prefix isn't displayed' ?")
print("Because in the UI, it's not drawn!")
print("For Hijacks, it uses `ce.CachedImpactStr` and it IS drawn.")
print("For Route Leaks, it uses `ce.CachedNetLabel` and `ce.CachedNetVal`.")
print("But `ce.CachedNetLabel` is populated from `ce.ImpactedPrefixes`.")
print("In `updateCriticalEventFromTransition`, does it set `ce.ImpactedPrefixes`?")
print("Wait, look at `updateCriticalEventFromTransition`.")
print("If it's a NEW transition, `createCriticalEventFromTransition` is called.")
print("```go\n    ce.ImpactedPrefixes[trans.Prefix] = struct{}{}\n```")
print("Then `e.updateCriticalEventCacheStrs(ce)` is called, which calls `cacheLeakStrings` for Route Leaks!")
print("But wait... look at `cacheLeakStrings`:")
print("```go\n    // Networks line\n    networks := make([]string, 0, len(ce.ImpactedPrefixes))\n    for p := range ce.ImpactedPrefixes {\n        networks = append(networks, p)\n    }\n    sort.Strings(networks)\n    ...\n    ce.CachedNetLabel = \"  Networks: \"\n    ce.CachedNetVal = netVal\n}\n```")
print("IT DOES THIS!")
print("Why would `ce.CachedNetVal` be empty?")
print("Wait... does `cacheLeakStrings` use `ce.ImpactedPrefixes`? No, wait!")
print("I truncated `sed -n '1653,1698p' pkg/bgpengine/engine.go` earlier!")
