print("Ah! It IS using `ce.CachedNetLabel` and `ce.CachedNetVal`!")
print("Wait... look at `ce.CachedNetVal`.")
print("If `networks` is empty, what happens?")
print("`netVal` is empty.")
print("Why would `networks` be empty?")
print("`networks := make([]string, 0, len(ce.ImpactedPrefixes))`")
print("`for p := range ce.ImpactedPrefixes { networks = append(networks, p) }`")
print("If `ce.ImpactedPrefixes` is empty?")
print("Why would `ce.ImpactedPrefixes` be empty for Hijack?")
print("Look at `updateCriticalEventFromTransition`:")
print("```go\nfunc (e *Engine) updateCriticalEventFromTransition(ce *CriticalEvent, trans *livemap.StateTransition) {\n    if ce.ImpactedPrefixes == nil {\n        ce.ImpactedPrefixes = make(map[string]struct{})\n    }\n    ...\n    if trans.Prefix != \"\" {\n        if _, ok := ce.ImpactedPrefixes[trans.Prefix]; !ok {\n            ce.ImpactedPrefixes[trans.Prefix] = struct{}{}\n            ce.ImpactedIPs += utils.GetPrefixSize(trans.Prefix)\n        }\n    }\n```")
print("Wait, `trans.Prefix` is `\"38.175.96.0/24\"` in the JSON payload.")
print("If `ce.ImpactedPrefixes` contains `trans.Prefix`, `networks` has 1 element.")
print("Then `netVal` is `38.175.96.0/24`.")
print("So `ce.CachedNetVal` should be `38.175.96.0/24`.")
print("Why would the prefix not be displayed?")
print("Wait! `cacheHijackDDoSStrings(ce)` is called WHEN the event is initially created!")
print("Is it called during UPDATE?")
print("```go\nfunc (e *Engine) RecordStateTransition(trans *livemap.StateTransition) {\n    ...\n    for _, ce := range e.CriticalStream {\n        if ce.Anom == anomName && ce.ASN == trans.Asn {\n            e.updateCriticalEventFromTransition(ce, trans)\n            updated = true\n            break\n        }\n    }\n```")
print("Wait! If `updated = true`, it calls `e.updateCriticalEventFromTransition(ce, trans)`.")
print("Does `updateCriticalEventFromTransition` call `e.updateCriticalEventCacheStrs(ce)`???")
print("Let's check!")
