print("Wait, look at lines 427-434 in `pkg/bgpengine/status.go`:")
print("```go\n    case bgp.NameRouteLeak, bgp.NameMinorRouteLeak:\n        if ce.LeakType != bgp.LeakUnknown {\n            // Leaker\n            nextY = e.drawRPKILine(e.streamClipBuffer, ce.CachedLeakerLabel, ce.LeakerRPKI, ce.CachedLeakerVal, e.subMonoFace, x+indent, nextY, boxW-indent-5, fontSize, labelCol, valueCol)\n```")
print("Wait!!! `if ce.LeakType != bgp.LeakUnknown`")
print("What is `ce.LeakType` initialized to?")
print("In `createCriticalEventFromTransition`, it maps `trans.LeakDetail.LeakType` to `ce.LeakType`.")
print("But for `ClassificationType::Hijack` we created a `LeakDetail` with `LeakType::None` (which maps to 0?).")
print("Wait, what about the route leak we saw?")
print("The JSON payload the user posted:")
print("```json\n    \"leakDetail\": {\n      \"leakerAsn\": 917,\n      \"victimAsn\": 57695\n    }\n```")
print("`leakType` is missing! That means `leakType` = 0 (default in protobuf).")
print("If `leakType` is 0, it maps to `bgp.LeakUnknown`?")
print("Let's look at `createCriticalEventFromTransition` in `pkg/bgpengine/engine.go`:")
