print("Ah! The user posted JSON output for a transition:")
print("`\"newState\": \"CLASSIFICATION_HIJACK\", \"oldState\": \"CLASSIFICATION_ROUTE_LEAK\"`")
print("Wait, if it transitioned FROM RouteLeak TO Hijack, what is `leakDetail`?")
print("It is the `leakDetail` OF THE NEW STATE! i.e., the Hijack!")
print("Because in `evaluate_prefix_state`, `leak_detail: if state.leak_type != LeakType::None { Some(LeakDetail { ... }) } else { None }`")
print("But wait! I added `leak_detail: Some(LeakDetail { leak_type: LeakType::None, ... })` to the Hijack `PendingEvent`!")
print("And because `leak_type` is `LeakType::None`, `state.leak_type != LeakType::None` will be FALSE in the future if we look at `state`!")
print("Wait... does `find_critical_anomaly` return `PendingEvent`?")
print("If the new state is Hijack, the `PendingEvent` contains `leak_detail: Some(...)` with `leak_type: LeakType::None`.")
print("But look at the JSON: `leakType` is MISSING. `leakerAsn` and `victimAsn` are present, but `leakerAsName` and `victimAsName` are MISSING.")
print("If `leaker_as_name` and `victim_as_name` were empty strings, they are omitted in JSON.")
print("So `get_as_name` returned empty strings for AS 917 and AS 57695.")
print("Wait, did `get_as_name` fallback work?")
print("If `i.name` is missing, it falls back to `i.as2org.map(|o| o.org_name)`.")
print("But what if `bgpkit.asinfo_get(asn)` returns `None` entirely? i.e. the ASN is NOT in the database at all?")
print("Then `get_as_name` returns `None`.")
print("And `.unwrap_or_default()` makes it an empty string `\"\"`.")
print("So the names are indeed empty strings.")

print("If the names are empty strings, the frontend should fall back to `ce.OrgID`!")
print("But `ce.OrgID` is `trans.AsName`.")
print("If `get_as_name` returned `None` for the attacker, then `trans.AsName` (which is `self.get_as_name(resolved_asn)`) will ALSO be an empty string!")
print("So `ce.OrgID` is ALSO empty!")
print("If `ce.OrgID` is empty, then `ce.CachedVictimVal` will be `ASxxx` (for Hijacks).")

print("Wait, the user says: 'The prefix isn't displayed and the names of the networks are not populated.'")
print("Prefix isn't displayed?!")
print("For HIJACK events:")
print("`case bgp.NameDDoSMitigation, bgp.NameHijack:`")
print("Does it draw the network line? `nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, ...)`")
print("What is `ce.CachedNetLabel` and `ce.CachedNetVal`?")
print("Wait! `cacheHijackDDoSStrings` calls `e.cacheImpactStrings(ce)`")
print("`cacheImpactStrings` sets `ce.CachedImpactStr = fmt.Sprintf(\"  Impact(%s): %s\", impactStr, pfxStr)`.")
print("But `ce.CachedNetLabel` is NOT set by `cacheImpactStrings`!")
print("`ce.CachedNetLabel` is NEVER set by `cacheHijackDDoSStrings`!")
print("If `ce.CachedNetLabel` is empty, what happens?")
print("In `status.go`: `nextY = e.drawLabeledLine(e.streamClipBuffer, ce.CachedNetLabel, ce.CachedNetVal, ...)`")
print("If `label` is empty, `drawLabeledLine` draws nothing or an empty string!")
print("Ah! `ce.CachedNetLabel` is only set in `cacheLeakStrings`: `ce.CachedNetLabel = \" Networks\"`, `ce.CachedNetVal = pfxStr`.")
print("For Hijack, I should use `ce.CachedImpactStr`! NOT `ce.CachedNetLabel` and `ce.CachedNetVal`!")
