print("Ah! The names are NOT empty! `i.name` is `\"MISAKA - Misaka Network, Inc.\"`")
print("So `get_as_name(917)` returned `Some(\"MISAKA - Misaka Network, Inc.\")`.")
print("If `get_as_name` returns a valid string, then why did the JSON have missing `leakerAsName` and `victimAsName`?")
print("Wait! Let's check `livemap.proto`.")
print("Maybe I spelled the fields wrong in `leak_detail`?")
print("```rust\nleaker_as_name: self.get_as_name(ctx.origin_asn).unwrap_or_default(),\nvictim_as_name: self.get_as_name(historical_origin_asn).unwrap_or_default(),\n```")
print("These are `String`s in Rust.")
print("How are they converted to Protobuf?")
print("In `pkg/bgpengine/engine.go`:")
print("`trans.LeakDetail.LeakerAsName`")
print("Wait! `livemap.proto` definition?")
