// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: historical/v1/historical.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyAsnArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Prefixes      []*PrefixHistory       `protobuf:"bytes,4,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyAsnArchive) Reset() {
	*x = DailyAsnArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyAsnArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyAsnArchive) ProtoMessage() {}

func (x *DailyAsnArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyAsnArchive.ProtoReflect.Descriptor instead.
func (*DailyAsnArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{0}
}

func (x *DailyAsnArchive) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *DailyAsnArchive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DailyAsnArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DailyAsnArchive) GetPrefixes() []*PrefixHistory {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type PrefixHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Events        []*Transition          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixHistory) Reset() {
	*x = PrefixHistory{}
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixHistory) ProtoMessage() {}

func (x *PrefixHistory) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixHistory.ProtoReflect.Descriptor instead.
func (*PrefixHistory) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{1}
}

func (x *PrefixHistory) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixHistory) GetEvents() []*Transition {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OldState       int32                  `protobuf:"varint,1,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState       int32                  `protobuf:"varint,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Ts             int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	IncidentId     string                 `protobuf:"bytes,4,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	LeakDetail     *HistLeakDetail        `protobuf:"bytes,5,opt,name=leak_detail,json=leakDetail,proto3" json:"leak_detail,omitempty"`
	AnomalyDetails string                 `protobuf:"bytes,6,opt,name=anomaly_details,json=anomalyDetails,proto3" json:"anomaly_details,omitempty"`
	RpkiStatus     int32                  `protobuf:"varint,7,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{2}
}

func (x *Transition) GetOldState() int32 {
	if x != nil {
		return x.OldState
	}
	return 0
}

func (x *Transition) GetNewState() int32 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *Transition) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Transition) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Transition) GetLeakDetail() *HistLeakDetail {
	if x != nil {
		return x.LeakDetail
	}
	return nil
}

func (x *Transition) GetAnomalyDetails() string {
	if x != nil {
		return x.AnomalyDetails
	}
	return ""
}

func (x *Transition) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type HistLeakDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeakType         string                 `protobuf:"bytes,1,opt,name=leak_type,json=leakType,proto3" json:"leak_type,omitempty"`
	LeakerAsn        uint32                 `protobuf:"varint,2,opt,name=leaker_asn,json=leakerAsn,proto3" json:"leaker_asn,omitempty"`
	LeakerName       string                 `protobuf:"bytes,3,opt,name=leaker_name,json=leakerName,proto3" json:"leaker_name,omitempty"`
	VictimAsn        uint32                 `protobuf:"varint,4,opt,name=victim_asn,json=victimAsn,proto3" json:"victim_asn,omitempty"`
	VictimName       string                 `protobuf:"bytes,5,opt,name=victim_name,json=victimName,proto3" json:"victim_name,omitempty"`
	LeakerRpkiStatus int32                  `protobuf:"varint,6,opt,name=leaker_rpki_status,json=leakerRpkiStatus,proto3" json:"leaker_rpki_status,omitempty"`
	VictimRpkiStatus int32                  `protobuf:"varint,7,opt,name=victim_rpki_status,json=victimRpkiStatus,proto3" json:"victim_rpki_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistLeakDetail) Reset() {
	*x = HistLeakDetail{}
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistLeakDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistLeakDetail) ProtoMessage() {}

func (x *HistLeakDetail) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistLeakDetail.ProtoReflect.Descriptor instead.
func (*HistLeakDetail) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{3}
}

func (x *HistLeakDetail) GetLeakType() string {
	if x != nil {
		return x.LeakType
	}
	return ""
}

func (x *HistLeakDetail) GetLeakerAsn() uint32 {
	if x != nil {
		return x.LeakerAsn
	}
	return 0
}

func (x *HistLeakDetail) GetLeakerName() string {
	if x != nil {
		return x.LeakerName
	}
	return ""
}

func (x *HistLeakDetail) GetVictimAsn() uint32 {
	if x != nil {
		return x.VictimAsn
	}
	return 0
}

func (x *HistLeakDetail) GetVictimName() string {
	if x != nil {
		return x.VictimName
	}
	return ""
}

func (x *HistLeakDetail) GetLeakerRpkiStatus() int32 {
	if x != nil {
		return x.LeakerRpkiStatus
	}
	return 0
}

func (x *HistLeakDetail) GetVictimRpkiStatus() int32 {
	if x != nil {
		return x.VictimRpkiStatus
	}
	return 0
}

type DaySummary struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Date             int64                    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"` // Unix timestamp for start of day
	TotalTransitions uint32                   `protobuf:"varint,2,opt,name=total_transitions,json=totalTransitions,proto3" json:"total_transitions,omitempty"`
	UniqueAsns       uint32                   `protobuf:"varint,3,opt,name=unique_asns,json=uniqueAsns,proto3" json:"unique_asns,omitempty"`
	UniquePrefixes   uint32                   `protobuf:"varint,4,opt,name=unique_prefixes,json=uniquePrefixes,proto3" json:"unique_prefixes,omitempty"`
	LatestEvents     []*HistTransitionSummary `protobuf:"bytes,5,rep,name=latest_events,json=latestEvents,proto3" json:"latest_events,omitempty"`
	UniqueOrgs       uint32                   `protobuf:"varint,6,opt,name=unique_orgs,json=uniqueOrgs,proto3" json:"unique_orgs,omitempty"`
	Ipv4PrefixCount  uint32                   `protobuf:"varint,7,opt,name=ipv4_prefix_count,json=ipv4PrefixCount,proto3" json:"ipv4_prefix_count,omitempty"`
	Ipv6PrefixCount  uint32                   `protobuf:"varint,8,opt,name=ipv6_prefix_count,json=ipv6PrefixCount,proto3" json:"ipv6_prefix_count,omitempty"`
	Ipv4Count        uint64                   `protobuf:"varint,9,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	RpkiValidIpv4    uint64                   `protobuf:"varint,10,opt,name=rpki_valid_ipv4,json=rpkiValidIpv4,proto3" json:"rpki_valid_ipv4,omitempty"`
	RpkiInvalidIpv4  uint64                   `protobuf:"varint,11,opt,name=rpki_invalid_ipv4,json=rpkiInvalidIpv4,proto3" json:"rpki_invalid_ipv4,omitempty"`
	RpkiNotFoundIpv4 uint64                   `protobuf:"varint,12,opt,name=rpki_not_found_ipv4,json=rpkiNotFoundIpv4,proto3" json:"rpki_not_found_ipv4,omitempty"`
	RpkiValidIpv6    uint64                   `protobuf:"varint,13,opt,name=rpki_valid_ipv6,json=rpkiValidIpv6,proto3" json:"rpki_valid_ipv6,omitempty"`
	RpkiInvalidIpv6  uint64                   `protobuf:"varint,14,opt,name=rpki_invalid_ipv6,json=rpkiInvalidIpv6,proto3" json:"rpki_invalid_ipv6,omitempty"`
	RpkiNotFoundIpv6 uint64                   `protobuf:"varint,15,opt,name=rpki_not_found_ipv6,json=rpkiNotFoundIpv6,proto3" json:"rpki_not_found_ipv6,omitempty"`
	FlappiestNetwork *HistFlappiestNetwork    `protobuf:"bytes,16,opt,name=flappiest_network,json=flappiestNetwork,proto3" json:"flappiest_network,omitempty"`
	TopAlerts        []*HistAlert             `protobuf:"bytes,17,rep,name=top_alerts,json=topAlerts,proto3" json:"top_alerts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DaySummary) Reset() {
	*x = DaySummary{}
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySummary) ProtoMessage() {}

func (x *DaySummary) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySummary.ProtoReflect.Descriptor instead.
func (*DaySummary) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{4}
}

func (x *DaySummary) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *DaySummary) GetTotalTransitions() uint32 {
	if x != nil {
		return x.TotalTransitions
	}
	return 0
}

func (x *DaySummary) GetUniqueAsns() uint32 {
	if x != nil {
		return x.UniqueAsns
	}
	return 0
}

func (x *DaySummary) GetUniquePrefixes() uint32 {
	if x != nil {
		return x.UniquePrefixes
	}
	return 0
}

func (x *DaySummary) GetLatestEvents() []*HistTransitionSummary {
	if x != nil {
		return x.LatestEvents
	}
	return nil
}

func (x *DaySummary) GetUniqueOrgs() uint32 {
	if x != nil {
		return x.UniqueOrgs
	}
	return 0
}

func (x *DaySummary) GetIpv4PrefixCount() uint32 {
	if x != nil {
		return x.Ipv4PrefixCount
	}
	return 0
}

func (x *DaySummary) GetIpv6PrefixCount() uint32 {
	if x != nil {
		return x.Ipv6PrefixCount
	}
	return 0
}

func (x *DaySummary) GetIpv4Count() uint64 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *DaySummary) GetRpkiValidIpv4() uint64 {
	if x != nil {
		return x.RpkiValidIpv4
	}
	return 0
}

func (x *DaySummary) GetRpkiInvalidIpv4() uint64 {
	if x != nil {
		return x.RpkiInvalidIpv4
	}
	return 0
}

func (x *DaySummary) GetRpkiNotFoundIpv4() uint64 {
	if x != nil {
		return x.RpkiNotFoundIpv4
	}
	return 0
}

func (x *DaySummary) GetRpkiValidIpv6() uint64 {
	if x != nil {
		return x.RpkiValidIpv6
	}
	return 0
}

func (x *DaySummary) GetRpkiInvalidIpv6() uint64 {
	if x != nil {
		return x.RpkiInvalidIpv6
	}
	return 0
}

func (x *DaySummary) GetRpkiNotFoundIpv6() uint64 {
	if x != nil {
		return x.RpkiNotFoundIpv6
	}
	return 0
}

func (x *DaySummary) GetFlappiestNetwork() *HistFlappiestNetwork {
	if x != nil {
		return x.FlappiestNetwork
	}
	return nil
}

func (x *DaySummary) GetTopAlerts() []*HistAlert {
	if x != nil {
		return x.TopAlerts
	}
	return nil
}

type HistAlertLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Lat           float32                `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,4,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusKm      float32                `protobuf:"fixed32,5,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistAlertLocation) Reset() {
	*x = HistAlertLocation{}
	mi := &file_historical_v1_historical_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistAlertLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistAlertLocation) ProtoMessage() {}

func (x *HistAlertLocation) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistAlertLocation.ProtoReflect.Descriptor instead.
func (*HistAlertLocation) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{5}
}

func (x *HistAlertLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *HistAlertLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *HistAlertLocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *HistAlertLocation) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *HistAlertLocation) GetRadiusKm() float32 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type HistAlert struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AlertType            int32                  `protobuf:"varint,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	Location             *HistAlertLocation     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Asn                  uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	Country              string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Classification       int32                  `protobuf:"varint,5,opt,name=classification,proto3" json:"classification,omitempty"`
	EventsCount          uint32                 `protobuf:"varint,6,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	Delta                int32                  `protobuf:"varint,7,opt,name=delta,proto3" json:"delta,omitempty"`
	Timestamp            int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ImpactedIpv4Ips      uint64                 `protobuf:"varint,9,opt,name=impacted_ipv4_ips,json=impactedIpv4Ips,proto3" json:"impacted_ipv4_ips,omitempty"`
	ImpactedIpv6Prefixes uint32                 `protobuf:"varint,10,opt,name=impacted_ipv6_prefixes,json=impactedIpv6Prefixes,proto3" json:"impacted_ipv6_prefixes,omitempty"`
	PercentageIncrease   float32                `protobuf:"fixed32,11,opt,name=percentage_increase,json=percentageIncrease,proto3" json:"percentage_increase,omitempty"`
	AsName               string                 `protobuf:"bytes,12,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Organization         string                 `protobuf:"bytes,13,opt,name=organization,proto3" json:"organization,omitempty"`
	AsnCount             uint32                 `protobuf:"varint,14,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	AnomalyScore         float32                `protobuf:"fixed32,15,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HistAlert) Reset() {
	*x = HistAlert{}
	mi := &file_historical_v1_historical_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistAlert) ProtoMessage() {}

func (x *HistAlert) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistAlert.ProtoReflect.Descriptor instead.
func (*HistAlert) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{6}
}

func (x *HistAlert) GetAlertType() int32 {
	if x != nil {
		return x.AlertType
	}
	return 0
}

func (x *HistAlert) GetLocation() *HistAlertLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *HistAlert) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *HistAlert) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *HistAlert) GetClassification() int32 {
	if x != nil {
		return x.Classification
	}
	return 0
}

func (x *HistAlert) GetEventsCount() uint32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *HistAlert) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *HistAlert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HistAlert) GetImpactedIpv4Ips() uint64 {
	if x != nil {
		return x.ImpactedIpv4Ips
	}
	return 0
}

func (x *HistAlert) GetImpactedIpv6Prefixes() uint32 {
	if x != nil {
		return x.ImpactedIpv6Prefixes
	}
	return 0
}

func (x *HistAlert) GetPercentageIncrease() float32 {
	if x != nil {
		return x.PercentageIncrease
	}
	return 0
}

func (x *HistAlert) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *HistAlert) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *HistAlert) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *HistAlert) GetAnomalyScore() float32 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

type HistFlappiestNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	NetworkName   string                 `protobuf:"bytes,2,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	EventRate     float32                `protobuf:"fixed32,3,opt,name=event_rate,json=eventRate,proto3" json:"event_rate,omitempty"`
	FlapCount     uint32                 `protobuf:"varint,4,opt,name=flap_count,json=flapCount,proto3" json:"flap_count,omitempty"`
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistFlappiestNetwork) Reset() {
	*x = HistFlappiestNetwork{}
	mi := &file_historical_v1_historical_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistFlappiestNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistFlappiestNetwork) ProtoMessage() {}

func (x *HistFlappiestNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistFlappiestNetwork.ProtoReflect.Descriptor instead.
func (*HistFlappiestNetwork) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{7}
}

func (x *HistFlappiestNetwork) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *HistFlappiestNetwork) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *HistFlappiestNetwork) GetEventRate() float32 {
	if x != nil {
		return x.EventRate
	}
	return 0
}

func (x *HistFlappiestNetwork) GetFlapCount() uint32 {
	if x != nil {
		return x.FlapCount
	}
	return 0
}

func (x *HistFlappiestNetwork) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type HistTransitionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	AsnName       string                 `protobuf:"bytes,2,opt,name=asn_name,json=asnName,proto3" json:"asn_name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OldState      int32                  `protobuf:"varint,5,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState      int32                  `protobuf:"varint,6,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Ts            int64                  `protobuf:"varint,7,opt,name=ts,proto3" json:"ts,omitempty"`
	RpkiStatus    int32                  `protobuf:"varint,8,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistTransitionSummary) Reset() {
	*x = HistTransitionSummary{}
	mi := &file_historical_v1_historical_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistTransitionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistTransitionSummary) ProtoMessage() {}

func (x *HistTransitionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistTransitionSummary.ProtoReflect.Descriptor instead.
func (*HistTransitionSummary) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{8}
}

func (x *HistTransitionSummary) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *HistTransitionSummary) GetAsnName() string {
	if x != nil {
		return x.AsnName
	}
	return ""
}

func (x *HistTransitionSummary) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *HistTransitionSummary) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *HistTransitionSummary) GetOldState() int32 {
	if x != nil {
		return x.OldState
	}
	return 0
}

func (x *HistTransitionSummary) GetNewState() int32 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *HistTransitionSummary) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *HistTransitionSummary) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type OrgArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Asns          []uint32               `protobuf:"varint,2,rep,packed,name=asns,proto3" json:"asns,omitempty"`
	EventCount    uint32                 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgArchive) Reset() {
	*x = OrgArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgArchive) ProtoMessage() {}

func (x *OrgArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgArchive.ProtoReflect.Descriptor instead.
func (*OrgArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{9}
}

func (x *OrgArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *OrgArchive) GetAsns() []uint32 {
	if x != nil {
		return x.Asns
	}
	return nil
}

func (x *OrgArchive) GetEventCount() uint32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type AsnMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	RpkiStatus    int32                  `protobuf:"varint,4,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsnMetadata) Reset() {
	*x = AsnMetadata{}
	mi := &file_historical_v1_historical_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsnMetadata) ProtoMessage() {}

func (x *AsnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsnMetadata.ProtoReflect.Descriptor instead.
func (*AsnMetadata) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{10}
}

func (x *AsnMetadata) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *AsnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsnMetadata) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *AsnMetadata) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type OrgMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgMetadata) Reset() {
	*x = OrgMetadata{}
	mi := &file_historical_v1_historical_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgMetadata) ProtoMessage() {}

func (x *OrgMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgMetadata.ProtoReflect.Descriptor instead.
func (*OrgMetadata) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{11}
}

func (x *OrgMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PrefixSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prefix         string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Classification int32                  `protobuf:"varint,2,opt,name=classification,proto3" json:"classification,omitempty"`
	Asn            uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	LastUpdateTs   int64                  `protobuf:"varint,4,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	TotalEvents    uint32                 `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrefixSnapshot) Reset() {
	*x = PrefixSnapshot{}
	mi := &file_historical_v1_historical_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixSnapshot) ProtoMessage() {}

func (x *PrefixSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixSnapshot.ProtoReflect.Descriptor instead.
func (*PrefixSnapshot) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{12}
}

func (x *PrefixSnapshot) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixSnapshot) GetClassification() int32 {
	if x != nil {
		return x.Classification
	}
	return 0
}

func (x *PrefixSnapshot) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *PrefixSnapshot) GetLastUpdateTs() int64 {
	if x != nil {
		return x.LastUpdateTs
	}
	return 0
}

func (x *PrefixSnapshot) GetTotalEvents() uint32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type GlobalMetadataIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asns          []*AsnMetadata         `protobuf:"bytes,1,rep,name=asns,proto3" json:"asns,omitempty"`
	Orgs          []*OrgMetadata         `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalMetadataIndex) Reset() {
	*x = GlobalMetadataIndex{}
	mi := &file_historical_v1_historical_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalMetadataIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMetadataIndex) ProtoMessage() {}

func (x *GlobalMetadataIndex) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMetadataIndex.ProtoReflect.Descriptor instead.
func (*GlobalMetadataIndex) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{13}
}

func (x *GlobalMetadataIndex) GetAsns() []*AsnMetadata {
	if x != nil {
		return x.Asns
	}
	return nil
}

func (x *GlobalMetadataIndex) GetOrgs() []*OrgMetadata {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type GlobalPrefixShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*PrefixSnapshot      `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalPrefixShard) Reset() {
	*x = GlobalPrefixShard{}
	mi := &file_historical_v1_historical_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalPrefixShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalPrefixShard) ProtoMessage() {}

func (x *GlobalPrefixShard) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalPrefixShard.ProtoReflect.Descriptor instead.
func (*GlobalPrefixShard) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{14}
}

func (x *GlobalPrefixShard) GetSnapshots() []*PrefixSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_historical_v1_historical_proto protoreflect.FileDescriptor

const file_historical_v1_historical_proto_rawDesc = "" +
	"\n" +
	"\x1ehistorical/v1/historical.proto\x12\rhistorical.v1\"\x83\x01\n" +
	"\x0fDailyAsnArchive\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x128\n" +
	"\bprefixes\x18\x04 \x03(\v2\x1c.historical.v1.PrefixHistoryR\bprefixes\"Z\n" +
	"\rPrefixHistory\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x121\n" +
	"\x06events\x18\x02 \x03(\v2\x19.historical.v1.TransitionR\x06events\"\x81\x02\n" +
	"\n" +
	"Transition\x12\x1b\n" +
	"\told_state\x18\x01 \x01(\x05R\boldState\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\x05R\bnewState\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x1f\n" +
	"\vincident_id\x18\x04 \x01(\tR\n" +
	"incidentId\x12>\n" +
	"\vleak_detail\x18\x05 \x01(\v2\x1d.historical.v1.HistLeakDetailR\n" +
	"leakDetail\x12'\n" +
	"\x0fanomaly_details\x18\x06 \x01(\tR\x0eanomalyDetails\x12\x1f\n" +
	"\vrpki_status\x18\a \x01(\x05R\n" +
	"rpkiStatus\"\x89\x02\n" +
	"\x0eHistLeakDetail\x12\x1b\n" +
	"\tleak_type\x18\x01 \x01(\tR\bleakType\x12\x1d\n" +
	"\n" +
	"leaker_asn\x18\x02 \x01(\rR\tleakerAsn\x12\x1f\n" +
	"\vleaker_name\x18\x03 \x01(\tR\n" +
	"leakerName\x12\x1d\n" +
	"\n" +
	"victim_asn\x18\x04 \x01(\rR\tvictimAsn\x12\x1f\n" +
	"\vvictim_name\x18\x05 \x01(\tR\n" +
	"victimName\x12,\n" +
	"\x12leaker_rpki_status\x18\x06 \x01(\x05R\x10leakerRpkiStatus\x12,\n" +
	"\x12victim_rpki_status\x18\a \x01(\x05R\x10victimRpkiStatus\"\x8b\x06\n" +
	"\n" +
	"DaySummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x03R\x04date\x12+\n" +
	"\x11total_transitions\x18\x02 \x01(\rR\x10totalTransitions\x12\x1f\n" +
	"\vunique_asns\x18\x03 \x01(\rR\n" +
	"uniqueAsns\x12'\n" +
	"\x0funique_prefixes\x18\x04 \x01(\rR\x0euniquePrefixes\x12I\n" +
	"\rlatest_events\x18\x05 \x03(\v2$.historical.v1.HistTransitionSummaryR\flatestEvents\x12\x1f\n" +
	"\vunique_orgs\x18\x06 \x01(\rR\n" +
	"uniqueOrgs\x12*\n" +
	"\x11ipv4_prefix_count\x18\a \x01(\rR\x0fipv4PrefixCount\x12*\n" +
	"\x11ipv6_prefix_count\x18\b \x01(\rR\x0fipv6PrefixCount\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\t \x01(\x04R\tipv4Count\x12&\n" +
	"\x0frpki_valid_ipv4\x18\n" +
	" \x01(\x04R\rrpkiValidIpv4\x12*\n" +
	"\x11rpki_invalid_ipv4\x18\v \x01(\x04R\x0frpkiInvalidIpv4\x12-\n" +
	"\x13rpki_not_found_ipv4\x18\f \x01(\x04R\x10rpkiNotFoundIpv4\x12&\n" +
	"\x0frpki_valid_ipv6\x18\r \x01(\x04R\rrpkiValidIpv6\x12*\n" +
	"\x11rpki_invalid_ipv6\x18\x0e \x01(\x04R\x0frpkiInvalidIpv6\x12-\n" +
	"\x13rpki_not_found_ipv6\x18\x0f \x01(\x04R\x10rpkiNotFoundIpv6\x12P\n" +
	"\x11flappiest_network\x18\x10 \x01(\v2#.historical.v1.HistFlappiestNetworkR\x10flappiestNetwork\x127\n" +
	"\n" +
	"top_alerts\x18\x11 \x03(\v2\x18.historical.v1.HistAlertR\ttopAlerts\"\x82\x01\n" +
	"\x11HistAlertLocation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x02R\x03lon\x12\x1b\n" +
	"\tradius_km\x18\x05 \x01(\x02R\bradiusKm\"\xa5\x04\n" +
	"\tHistAlert\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\x05R\talertType\x12<\n" +
	"\blocation\x18\x02 \x01(\v2 .historical.v1.HistAlertLocationR\blocation\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12&\n" +
	"\x0eclassification\x18\x05 \x01(\x05R\x0eclassification\x12!\n" +
	"\fevents_count\x18\x06 \x01(\rR\veventsCount\x12\x14\n" +
	"\x05delta\x18\a \x01(\x05R\x05delta\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12*\n" +
	"\x11impacted_ipv4_ips\x18\t \x01(\x04R\x0fimpactedIpv4Ips\x124\n" +
	"\x16impacted_ipv6_prefixes\x18\n" +
	" \x01(\rR\x14impactedIpv6Prefixes\x12/\n" +
	"\x13percentage_increase\x18\v \x01(\x02R\x12percentageIncrease\x12\x17\n" +
	"\aas_name\x18\f \x01(\tR\x06asName\x12\"\n" +
	"\forganization\x18\r \x01(\tR\forganization\x12\x1b\n" +
	"\tasn_count\x18\x0e \x01(\rR\basnCount\x12#\n" +
	"\ranomaly_score\x18\x0f \x01(\x02R\fanomalyScore\"\xa1\x01\n" +
	"\x14HistFlappiestNetwork\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12!\n" +
	"\fnetwork_name\x18\x02 \x01(\tR\vnetworkName\x12\x1d\n" +
	"\n" +
	"event_rate\x18\x03 \x01(\x02R\teventRate\x12\x1d\n" +
	"\n" +
	"flap_count\x18\x04 \x01(\rR\tflapCount\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\"\xd9\x01\n" +
	"\x15HistTransitionSummary\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x19\n" +
	"\basn_name\x18\x02 \x01(\tR\aasnName\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x1b\n" +
	"\told_state\x18\x05 \x01(\x05R\boldState\x12\x1b\n" +
	"\tnew_state\x18\x06 \x01(\x05R\bnewState\x12\x0e\n" +
	"\x02ts\x18\a \x01(\x03R\x02ts\x12\x1f\n" +
	"\vrpki_status\x18\b \x01(\x05R\n" +
	"rpkiStatus\"S\n" +
	"\n" +
	"OrgArchive\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04asns\x18\x02 \x03(\rR\x04asns\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\rR\n" +
	"eventCount\"f\n" +
	"\vAsnMetadata\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x1f\n" +
	"\vrpki_status\x18\x04 \x01(\x05R\n" +
	"rpkiStatus\"5\n" +
	"\vOrgMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\xab\x01\n" +
	"\x0ePrefixSnapshot\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12&\n" +
	"\x0eclassification\x18\x02 \x01(\x05R\x0eclassification\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12$\n" +
	"\x0elast_update_ts\x18\x04 \x01(\x03R\flastUpdateTs\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\rR\vtotalEvents\"u\n" +
	"\x13GlobalMetadataIndex\x12.\n" +
	"\x04asns\x18\x01 \x03(\v2\x1a.historical.v1.AsnMetadataR\x04asns\x12.\n" +
	"\x04orgs\x18\x02 \x03(\v2\x1a.historical.v1.OrgMetadataR\x04orgs\"P\n" +
	"\x11GlobalPrefixShard\x12;\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1d.historical.v1.PrefixSnapshotR\tsnapshotsB\xb5\x01\n" +
	"\x11com.historical.v1B\x0fHistoricalProtoP\x01Z:github.com/sudorandom/bgp-stream/pkg/livemap/historical/v1\xa2\x02\x03HXX\xaa\x02\rHistorical.V1\xca\x02\rHistorical\\V1\xe2\x02\x19Historical\\V1\\GPBMetadata\xea\x02\x0eHistorical::V1b\x06proto3"

var (
	file_historical_v1_historical_proto_rawDescOnce sync.Once
	file_historical_v1_historical_proto_rawDescData []byte
)

func file_historical_v1_historical_proto_rawDescGZIP() []byte {
	file_historical_v1_historical_proto_rawDescOnce.Do(func() {
		file_historical_v1_historical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)))
	})
	return file_historical_v1_historical_proto_rawDescData
}

var file_historical_v1_historical_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_historical_v1_historical_proto_goTypes = []any{
	(*DailyAsnArchive)(nil),       // 0: historical.v1.DailyAsnArchive
	(*PrefixHistory)(nil),         // 1: historical.v1.PrefixHistory
	(*Transition)(nil),            // 2: historical.v1.Transition
	(*HistLeakDetail)(nil),        // 3: historical.v1.HistLeakDetail
	(*DaySummary)(nil),            // 4: historical.v1.DaySummary
	(*HistAlertLocation)(nil),     // 5: historical.v1.HistAlertLocation
	(*HistAlert)(nil),             // 6: historical.v1.HistAlert
	(*HistFlappiestNetwork)(nil),  // 7: historical.v1.HistFlappiestNetwork
	(*HistTransitionSummary)(nil), // 8: historical.v1.HistTransitionSummary
	(*OrgArchive)(nil),            // 9: historical.v1.OrgArchive
	(*AsnMetadata)(nil),           // 10: historical.v1.AsnMetadata
	(*OrgMetadata)(nil),           // 11: historical.v1.OrgMetadata
	(*PrefixSnapshot)(nil),        // 12: historical.v1.PrefixSnapshot
	(*GlobalMetadataIndex)(nil),   // 13: historical.v1.GlobalMetadataIndex
	(*GlobalPrefixShard)(nil),     // 14: historical.v1.GlobalPrefixShard
}
var file_historical_v1_historical_proto_depIdxs = []int32{
	1,  // 0: historical.v1.DailyAsnArchive.prefixes:type_name -> historical.v1.PrefixHistory
	2,  // 1: historical.v1.PrefixHistory.events:type_name -> historical.v1.Transition
	3,  // 2: historical.v1.Transition.leak_detail:type_name -> historical.v1.HistLeakDetail
	8,  // 3: historical.v1.DaySummary.latest_events:type_name -> historical.v1.HistTransitionSummary
	7,  // 4: historical.v1.DaySummary.flappiest_network:type_name -> historical.v1.HistFlappiestNetwork
	6,  // 5: historical.v1.DaySummary.top_alerts:type_name -> historical.v1.HistAlert
	5,  // 6: historical.v1.HistAlert.location:type_name -> historical.v1.HistAlertLocation
	10, // 7: historical.v1.GlobalMetadataIndex.asns:type_name -> historical.v1.AsnMetadata
	11, // 8: historical.v1.GlobalMetadataIndex.orgs:type_name -> historical.v1.OrgMetadata
	12, // 9: historical.v1.GlobalPrefixShard.snapshots:type_name -> historical.v1.PrefixSnapshot
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_historical_v1_historical_proto_init() }
func file_historical_v1_historical_proto_init() {
	if File_historical_v1_historical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_historical_v1_historical_proto_goTypes,
		DependencyIndexes: file_historical_v1_historical_proto_depIdxs,
		MessageInfos:      file_historical_v1_historical_proto_msgTypes,
	}.Build()
	File_historical_v1_historical_proto = out.File
	file_historical_v1_historical_proto_goTypes = nil
	file_historical_v1_historical_proto_depIdxs = nil
}
