// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: historical/v1/historical.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyAsnArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Prefixes      []*PrefixHistory       `protobuf:"bytes,4,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyAsnArchive) Reset() {
	*x = DailyAsnArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyAsnArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyAsnArchive) ProtoMessage() {}

func (x *DailyAsnArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyAsnArchive.ProtoReflect.Descriptor instead.
func (*DailyAsnArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{0}
}

func (x *DailyAsnArchive) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *DailyAsnArchive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DailyAsnArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DailyAsnArchive) GetPrefixes() []*PrefixHistory {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type PrefixHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Events        []*Transition          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixHistory) Reset() {
	*x = PrefixHistory{}
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixHistory) ProtoMessage() {}

func (x *PrefixHistory) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixHistory.ProtoReflect.Descriptor instead.
func (*PrefixHistory) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{1}
}

func (x *PrefixHistory) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixHistory) GetEvents() []*Transition {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OldState       int32                  `protobuf:"varint,1,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState       int32                  `protobuf:"varint,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Ts             int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	IncidentId     string                 `protobuf:"bytes,4,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	LeakDetail     *HistLeakDetail        `protobuf:"bytes,5,opt,name=leak_detail,json=leakDetail,proto3" json:"leak_detail,omitempty"`
	AnomalyDetails string                 `protobuf:"bytes,6,opt,name=anomaly_details,json=anomalyDetails,proto3" json:"anomaly_details,omitempty"`
	RpkiStatus     int32                  `protobuf:"varint,7,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{2}
}

func (x *Transition) GetOldState() int32 {
	if x != nil {
		return x.OldState
	}
	return 0
}

func (x *Transition) GetNewState() int32 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *Transition) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Transition) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Transition) GetLeakDetail() *HistLeakDetail {
	if x != nil {
		return x.LeakDetail
	}
	return nil
}

func (x *Transition) GetAnomalyDetails() string {
	if x != nil {
		return x.AnomalyDetails
	}
	return ""
}

func (x *Transition) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type HistLeakDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeakType         string                 `protobuf:"bytes,1,opt,name=leak_type,json=leakType,proto3" json:"leak_type,omitempty"`
	LeakerAsn        uint32                 `protobuf:"varint,2,opt,name=leaker_asn,json=leakerAsn,proto3" json:"leaker_asn,omitempty"`
	LeakerName       string                 `protobuf:"bytes,3,opt,name=leaker_name,json=leakerName,proto3" json:"leaker_name,omitempty"`
	VictimAsn        uint32                 `protobuf:"varint,4,opt,name=victim_asn,json=victimAsn,proto3" json:"victim_asn,omitempty"`
	VictimName       string                 `protobuf:"bytes,5,opt,name=victim_name,json=victimName,proto3" json:"victim_name,omitempty"`
	LeakerRpkiStatus int32                  `protobuf:"varint,6,opt,name=leaker_rpki_status,json=leakerRpkiStatus,proto3" json:"leaker_rpki_status,omitempty"`
	VictimRpkiStatus int32                  `protobuf:"varint,7,opt,name=victim_rpki_status,json=victimRpkiStatus,proto3" json:"victim_rpki_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistLeakDetail) Reset() {
	*x = HistLeakDetail{}
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistLeakDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistLeakDetail) ProtoMessage() {}

func (x *HistLeakDetail) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistLeakDetail.ProtoReflect.Descriptor instead.
func (*HistLeakDetail) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{3}
}

func (x *HistLeakDetail) GetLeakType() string {
	if x != nil {
		return x.LeakType
	}
	return ""
}

func (x *HistLeakDetail) GetLeakerAsn() uint32 {
	if x != nil {
		return x.LeakerAsn
	}
	return 0
}

func (x *HistLeakDetail) GetLeakerName() string {
	if x != nil {
		return x.LeakerName
	}
	return ""
}

func (x *HistLeakDetail) GetVictimAsn() uint32 {
	if x != nil {
		return x.VictimAsn
	}
	return 0
}

func (x *HistLeakDetail) GetVictimName() string {
	if x != nil {
		return x.VictimName
	}
	return ""
}

func (x *HistLeakDetail) GetLeakerRpkiStatus() int32 {
	if x != nil {
		return x.LeakerRpkiStatus
	}
	return 0
}

func (x *HistLeakDetail) GetVictimRpkiStatus() int32 {
	if x != nil {
		return x.VictimRpkiStatus
	}
	return 0
}

type DaySummary struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Date             int64                    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"` // Unix timestamp for start of day
	TotalTransitions uint32                   `protobuf:"varint,2,opt,name=total_transitions,json=totalTransitions,proto3" json:"total_transitions,omitempty"`
	UniqueAsns       uint32                   `protobuf:"varint,3,opt,name=unique_asns,json=uniqueAsns,proto3" json:"unique_asns,omitempty"`
	UniquePrefixes   uint32                   `protobuf:"varint,4,opt,name=unique_prefixes,json=uniquePrefixes,proto3" json:"unique_prefixes,omitempty"`
	LatestEvents     []*HistTransitionSummary `protobuf:"bytes,5,rep,name=latest_events,json=latestEvents,proto3" json:"latest_events,omitempty"`
	UniqueOrgs       uint32                   `protobuf:"varint,6,opt,name=unique_orgs,json=uniqueOrgs,proto3" json:"unique_orgs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DaySummary) Reset() {
	*x = DaySummary{}
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySummary) ProtoMessage() {}

func (x *DaySummary) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySummary.ProtoReflect.Descriptor instead.
func (*DaySummary) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{4}
}

func (x *DaySummary) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *DaySummary) GetTotalTransitions() uint32 {
	if x != nil {
		return x.TotalTransitions
	}
	return 0
}

func (x *DaySummary) GetUniqueAsns() uint32 {
	if x != nil {
		return x.UniqueAsns
	}
	return 0
}

func (x *DaySummary) GetUniquePrefixes() uint32 {
	if x != nil {
		return x.UniquePrefixes
	}
	return 0
}

func (x *DaySummary) GetLatestEvents() []*HistTransitionSummary {
	if x != nil {
		return x.LatestEvents
	}
	return nil
}

func (x *DaySummary) GetUniqueOrgs() uint32 {
	if x != nil {
		return x.UniqueOrgs
	}
	return 0
}

type HistTransitionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	AsnName       string                 `protobuf:"bytes,2,opt,name=asn_name,json=asnName,proto3" json:"asn_name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OldState      int32                  `protobuf:"varint,5,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState      int32                  `protobuf:"varint,6,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Ts            int64                  `protobuf:"varint,7,opt,name=ts,proto3" json:"ts,omitempty"`
	RpkiStatus    int32                  `protobuf:"varint,8,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistTransitionSummary) Reset() {
	*x = HistTransitionSummary{}
	mi := &file_historical_v1_historical_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistTransitionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistTransitionSummary) ProtoMessage() {}

func (x *HistTransitionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistTransitionSummary.ProtoReflect.Descriptor instead.
func (*HistTransitionSummary) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{5}
}

func (x *HistTransitionSummary) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *HistTransitionSummary) GetAsnName() string {
	if x != nil {
		return x.AsnName
	}
	return ""
}

func (x *HistTransitionSummary) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *HistTransitionSummary) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *HistTransitionSummary) GetOldState() int32 {
	if x != nil {
		return x.OldState
	}
	return 0
}

func (x *HistTransitionSummary) GetNewState() int32 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *HistTransitionSummary) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *HistTransitionSummary) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type OrgArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Asns          []uint32               `protobuf:"varint,2,rep,packed,name=asns,proto3" json:"asns,omitempty"`
	EventCount    uint32                 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgArchive) Reset() {
	*x = OrgArchive{}
	mi := &file_historical_v1_historical_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgArchive) ProtoMessage() {}

func (x *OrgArchive) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgArchive.ProtoReflect.Descriptor instead.
func (*OrgArchive) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{6}
}

func (x *OrgArchive) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *OrgArchive) GetAsns() []uint32 {
	if x != nil {
		return x.Asns
	}
	return nil
}

func (x *OrgArchive) GetEventCount() uint32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type AsnMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	RpkiStatus    int32                  `protobuf:"varint,4,opt,name=rpki_status,json=rpkiStatus,proto3" json:"rpki_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsnMetadata) Reset() {
	*x = AsnMetadata{}
	mi := &file_historical_v1_historical_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsnMetadata) ProtoMessage() {}

func (x *AsnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsnMetadata.ProtoReflect.Descriptor instead.
func (*AsnMetadata) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{7}
}

func (x *AsnMetadata) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *AsnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsnMetadata) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *AsnMetadata) GetRpkiStatus() int32 {
	if x != nil {
		return x.RpkiStatus
	}
	return 0
}

type OrgMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgMetadata) Reset() {
	*x = OrgMetadata{}
	mi := &file_historical_v1_historical_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgMetadata) ProtoMessage() {}

func (x *OrgMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgMetadata.ProtoReflect.Descriptor instead.
func (*OrgMetadata) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{8}
}

func (x *OrgMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PrefixSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prefix         string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Classification int32                  `protobuf:"varint,2,opt,name=classification,proto3" json:"classification,omitempty"`
	Asn            uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	LastUpdateTs   int64                  `protobuf:"varint,4,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	TotalEvents    uint32                 `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrefixSnapshot) Reset() {
	*x = PrefixSnapshot{}
	mi := &file_historical_v1_historical_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixSnapshot) ProtoMessage() {}

func (x *PrefixSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixSnapshot.ProtoReflect.Descriptor instead.
func (*PrefixSnapshot) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{9}
}

func (x *PrefixSnapshot) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixSnapshot) GetClassification() int32 {
	if x != nil {
		return x.Classification
	}
	return 0
}

func (x *PrefixSnapshot) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *PrefixSnapshot) GetLastUpdateTs() int64 {
	if x != nil {
		return x.LastUpdateTs
	}
	return 0
}

func (x *PrefixSnapshot) GetTotalEvents() uint32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type GlobalMetadataIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asns          []*AsnMetadata         `protobuf:"bytes,1,rep,name=asns,proto3" json:"asns,omitempty"`
	Orgs          []*OrgMetadata         `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalMetadataIndex) Reset() {
	*x = GlobalMetadataIndex{}
	mi := &file_historical_v1_historical_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalMetadataIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMetadataIndex) ProtoMessage() {}

func (x *GlobalMetadataIndex) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMetadataIndex.ProtoReflect.Descriptor instead.
func (*GlobalMetadataIndex) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalMetadataIndex) GetAsns() []*AsnMetadata {
	if x != nil {
		return x.Asns
	}
	return nil
}

func (x *GlobalMetadataIndex) GetOrgs() []*OrgMetadata {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type GlobalPrefixShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*PrefixSnapshot      `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalPrefixShard) Reset() {
	*x = GlobalPrefixShard{}
	mi := &file_historical_v1_historical_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalPrefixShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalPrefixShard) ProtoMessage() {}

func (x *GlobalPrefixShard) ProtoReflect() protoreflect.Message {
	mi := &file_historical_v1_historical_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalPrefixShard.ProtoReflect.Descriptor instead.
func (*GlobalPrefixShard) Descriptor() ([]byte, []int) {
	return file_historical_v1_historical_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalPrefixShard) GetSnapshots() []*PrefixSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_historical_v1_historical_proto protoreflect.FileDescriptor

const file_historical_v1_historical_proto_rawDesc = "" +
	"\n" +
	"\x1ehistorical/v1/historical.proto\x12\rhistorical.v1\"\x83\x01\n" +
	"\x0fDailyAsnArchive\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x128\n" +
	"\bprefixes\x18\x04 \x03(\v2\x1c.historical.v1.PrefixHistoryR\bprefixes\"Z\n" +
	"\rPrefixHistory\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x121\n" +
	"\x06events\x18\x02 \x03(\v2\x19.historical.v1.TransitionR\x06events\"\x81\x02\n" +
	"\n" +
	"Transition\x12\x1b\n" +
	"\told_state\x18\x01 \x01(\x05R\boldState\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\x05R\bnewState\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x1f\n" +
	"\vincident_id\x18\x04 \x01(\tR\n" +
	"incidentId\x12>\n" +
	"\vleak_detail\x18\x05 \x01(\v2\x1d.historical.v1.HistLeakDetailR\n" +
	"leakDetail\x12'\n" +
	"\x0fanomaly_details\x18\x06 \x01(\tR\x0eanomalyDetails\x12\x1f\n" +
	"\vrpki_status\x18\a \x01(\x05R\n" +
	"rpkiStatus\"\x89\x02\n" +
	"\x0eHistLeakDetail\x12\x1b\n" +
	"\tleak_type\x18\x01 \x01(\tR\bleakType\x12\x1d\n" +
	"\n" +
	"leaker_asn\x18\x02 \x01(\rR\tleakerAsn\x12\x1f\n" +
	"\vleaker_name\x18\x03 \x01(\tR\n" +
	"leakerName\x12\x1d\n" +
	"\n" +
	"victim_asn\x18\x04 \x01(\rR\tvictimAsn\x12\x1f\n" +
	"\vvictim_name\x18\x05 \x01(\tR\n" +
	"victimName\x12,\n" +
	"\x12leaker_rpki_status\x18\x06 \x01(\x05R\x10leakerRpkiStatus\x12,\n" +
	"\x12victim_rpki_status\x18\a \x01(\x05R\x10victimRpkiStatus\"\x83\x02\n" +
	"\n" +
	"DaySummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x03R\x04date\x12+\n" +
	"\x11total_transitions\x18\x02 \x01(\rR\x10totalTransitions\x12\x1f\n" +
	"\vunique_asns\x18\x03 \x01(\rR\n" +
	"uniqueAsns\x12'\n" +
	"\x0funique_prefixes\x18\x04 \x01(\rR\x0euniquePrefixes\x12I\n" +
	"\rlatest_events\x18\x05 \x03(\v2$.historical.v1.HistTransitionSummaryR\flatestEvents\x12\x1f\n" +
	"\vunique_orgs\x18\x06 \x01(\rR\n" +
	"uniqueOrgs\"\xd9\x01\n" +
	"\x15HistTransitionSummary\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x19\n" +
	"\basn_name\x18\x02 \x01(\tR\aasnName\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x1b\n" +
	"\told_state\x18\x05 \x01(\x05R\boldState\x12\x1b\n" +
	"\tnew_state\x18\x06 \x01(\x05R\bnewState\x12\x0e\n" +
	"\x02ts\x18\a \x01(\x03R\x02ts\x12\x1f\n" +
	"\vrpki_status\x18\b \x01(\x05R\n" +
	"rpkiStatus\"S\n" +
	"\n" +
	"OrgArchive\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04asns\x18\x02 \x03(\rR\x04asns\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\rR\n" +
	"eventCount\"f\n" +
	"\vAsnMetadata\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x1f\n" +
	"\vrpki_status\x18\x04 \x01(\x05R\n" +
	"rpkiStatus\"5\n" +
	"\vOrgMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\xab\x01\n" +
	"\x0ePrefixSnapshot\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12&\n" +
	"\x0eclassification\x18\x02 \x01(\x05R\x0eclassification\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12$\n" +
	"\x0elast_update_ts\x18\x04 \x01(\x03R\flastUpdateTs\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\rR\vtotalEvents\"u\n" +
	"\x13GlobalMetadataIndex\x12.\n" +
	"\x04asns\x18\x01 \x03(\v2\x1a.historical.v1.AsnMetadataR\x04asns\x12.\n" +
	"\x04orgs\x18\x02 \x03(\v2\x1a.historical.v1.OrgMetadataR\x04orgs\"P\n" +
	"\x11GlobalPrefixShard\x12;\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1d.historical.v1.PrefixSnapshotR\tsnapshotsB\xb5\x01\n" +
	"\x11com.historical.v1B\x0fHistoricalProtoP\x01Z:github.com/sudorandom/bgp-stream/pkg/livemap/historical/v1\xa2\x02\x03HXX\xaa\x02\rHistorical.V1\xca\x02\rHistorical\\V1\xe2\x02\x19Historical\\V1\\GPBMetadata\xea\x02\x0eHistorical::V1b\x06proto3"

var (
	file_historical_v1_historical_proto_rawDescOnce sync.Once
	file_historical_v1_historical_proto_rawDescData []byte
)

func file_historical_v1_historical_proto_rawDescGZIP() []byte {
	file_historical_v1_historical_proto_rawDescOnce.Do(func() {
		file_historical_v1_historical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)))
	})
	return file_historical_v1_historical_proto_rawDescData
}

var file_historical_v1_historical_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_historical_v1_historical_proto_goTypes = []any{
	(*DailyAsnArchive)(nil),       // 0: historical.v1.DailyAsnArchive
	(*PrefixHistory)(nil),         // 1: historical.v1.PrefixHistory
	(*Transition)(nil),            // 2: historical.v1.Transition
	(*HistLeakDetail)(nil),        // 3: historical.v1.HistLeakDetail
	(*DaySummary)(nil),            // 4: historical.v1.DaySummary
	(*HistTransitionSummary)(nil), // 5: historical.v1.HistTransitionSummary
	(*OrgArchive)(nil),            // 6: historical.v1.OrgArchive
	(*AsnMetadata)(nil),           // 7: historical.v1.AsnMetadata
	(*OrgMetadata)(nil),           // 8: historical.v1.OrgMetadata
	(*PrefixSnapshot)(nil),        // 9: historical.v1.PrefixSnapshot
	(*GlobalMetadataIndex)(nil),   // 10: historical.v1.GlobalMetadataIndex
	(*GlobalPrefixShard)(nil),     // 11: historical.v1.GlobalPrefixShard
}
var file_historical_v1_historical_proto_depIdxs = []int32{
	1, // 0: historical.v1.DailyAsnArchive.prefixes:type_name -> historical.v1.PrefixHistory
	2, // 1: historical.v1.PrefixHistory.events:type_name -> historical.v1.Transition
	3, // 2: historical.v1.Transition.leak_detail:type_name -> historical.v1.HistLeakDetail
	5, // 3: historical.v1.DaySummary.latest_events:type_name -> historical.v1.HistTransitionSummary
	7, // 4: historical.v1.GlobalMetadataIndex.asns:type_name -> historical.v1.AsnMetadata
	8, // 5: historical.v1.GlobalMetadataIndex.orgs:type_name -> historical.v1.OrgMetadata
	9, // 6: historical.v1.GlobalPrefixShard.snapshots:type_name -> historical.v1.PrefixSnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_historical_v1_historical_proto_init() }
func file_historical_v1_historical_proto_init() {
	if File_historical_v1_historical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historical_v1_historical_proto_rawDesc), len(file_historical_v1_historical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_historical_v1_historical_proto_goTypes,
		DependencyIndexes: file_historical_v1_historical_proto_depIdxs,
		MessageInfos:      file_historical_v1_historical_proto_msgTypes,
	}.Build()
	File_historical_v1_historical_proto = out.File
	file_historical_v1_historical_proto_goTypes = nil
	file_historical_v1_historical_proto_depIdxs = nil
}
