// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/livemap.proto

package livemap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiveMap_SubscribeEvents_FullMethodName        = "/livemap.LiveMap/SubscribeEvents"
	LiveMap_GetSummary_FullMethodName             = "/livemap.LiveMap/GetSummary"
	LiveMap_StreamStateTransitions_FullMethodName = "/livemap.LiveMap/StreamStateTransitions"
)

// LiveMapClient is the client API for LiveMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveMapClient interface {
	SubscribeEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
	GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
	StreamStateTransitions(ctx context.Context, in *StreamStateTransitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamStateTransitionsResponse], error)
}

type liveMapClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveMapClient(cc grpc.ClientConnInterface) LiveMapClient {
	return &liveMapClient{cc}
}

func (c *liveMapClient) SubscribeEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMap_ServiceDesc.Streams[0], LiveMap_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMap_SubscribeEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

func (c *liveMapClient) GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, LiveMap_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveMapClient) StreamStateTransitions(ctx context.Context, in *StreamStateTransitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamStateTransitionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveMap_ServiceDesc.Streams[1], LiveMap_StreamStateTransitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStateTransitionsRequest, StreamStateTransitionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMap_StreamStateTransitionsClient = grpc.ServerStreamingClient[StreamStateTransitionsResponse]

// LiveMapServer is the server API for LiveMap service.
// All implementations must embed UnimplementedLiveMapServer
// for forward compatibility.
type LiveMapServer interface {
	SubscribeEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	StreamStateTransitions(*StreamStateTransitionsRequest, grpc.ServerStreamingServer[StreamStateTransitionsResponse]) error
	mustEmbedUnimplementedLiveMapServer()
}

// UnimplementedLiveMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveMapServer struct{}

func (UnimplementedLiveMapServer) SubscribeEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedLiveMapServer) GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedLiveMapServer) StreamStateTransitions(*StreamStateTransitionsRequest, grpc.ServerStreamingServer[StreamStateTransitionsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStateTransitions not implemented")
}
func (UnimplementedLiveMapServer) mustEmbedUnimplementedLiveMapServer() {}
func (UnimplementedLiveMapServer) testEmbeddedByValue()                 {}

// UnsafeLiveMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveMapServer will
// result in compilation errors.
type UnsafeLiveMapServer interface {
	mustEmbedUnimplementedLiveMapServer()
}

func RegisterLiveMapServer(s grpc.ServiceRegistrar, srv LiveMapServer) {
	// If the following call panics, it indicates UnimplementedLiveMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiveMap_ServiceDesc, srv)
}

func _LiveMap_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServer).SubscribeEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMap_SubscribeEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

func _LiveMap_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveMapServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveMap_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveMapServer).GetSummary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveMap_StreamStateTransitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStateTransitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiveMapServer).StreamStateTransitions(m, &grpc.GenericServerStream[StreamStateTransitionsRequest, StreamStateTransitionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveMap_StreamStateTransitionsServer = grpc.ServerStreamingServer[StreamStateTransitionsResponse]

// LiveMap_ServiceDesc is the grpc.ServiceDesc for LiveMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livemap.LiveMap",
	HandlerType: (*LiveMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _LiveMap_GetSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _LiveMap_SubscribeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStateTransitions",
			Handler:       _LiveMap_StreamStateTransitions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/livemap.proto",
}
