// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/livemap.proto

package livemap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Classification int32

const (
	Classification_NONE                Classification = 0
	Classification_BOGON               Classification = 1
	Classification_HIJACK              Classification = 2
	Classification_ROUTE_LEAK          Classification = 3
	Classification_OUTAGE              Classification = 4
	Classification_DDOS_MITIGATION     Classification = 5
	Classification_FLAP                Classification = 6
	Classification_TRAFFIC_ENGINEERING Classification = 7
	Classification_PATH_HUNTING        Classification = 8
	Classification_DISCOVERY           Classification = 9
)

// Enum value maps for Classification.
var (
	Classification_name = map[int32]string{
		0: "NONE",
		1: "BOGON",
		2: "HIJACK",
		3: "ROUTE_LEAK",
		4: "OUTAGE",
		5: "DDOS_MITIGATION",
		6: "FLAP",
		7: "TRAFFIC_ENGINEERING",
		8: "PATH_HUNTING",
		9: "DISCOVERY",
	}
	Classification_value = map[string]int32{
		"NONE":                0,
		"BOGON":               1,
		"HIJACK":              2,
		"ROUTE_LEAK":          3,
		"OUTAGE":              4,
		"DDOS_MITIGATION":     5,
		"FLAP":                6,
		"TRAFFIC_ENGINEERING": 7,
		"PATH_HUNTING":        8,
		"DISCOVERY":           9,
	}
)

func (x Classification) Enum() *Classification {
	p := new(Classification)
	*p = x
	return p
}

func (x Classification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Classification) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_livemap_proto_enumTypes[0].Descriptor()
}

func (Classification) Type() protoreflect.EnumType {
	return &file_proto_livemap_proto_enumTypes[0]
}

func (x Classification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Classification.Descriptor instead.
func (Classification) EnumDescriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{0}
}

type GeoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoData) Reset() {
	*x = GeoData{}
	mi := &file_proto_livemap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoData) ProtoMessage() {}

func (x *GeoData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoData.ProtoReflect.Descriptor instead.
func (*GeoData) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{0}
}

func (x *GeoData) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoData) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type AggregatedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Geo            *GeoData               `protobuf:"bytes,1,opt,name=geo,proto3" json:"geo,omitempty"`
	Classification Classification         `protobuf:"varint,2,opt,name=classification,proto3,enum=livemap.Classification" json:"classification,omitempty"`
	Count          uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregatedEvent) Reset() {
	*x = AggregatedEvent{}
	mi := &file_proto_livemap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedEvent) ProtoMessage() {}

func (x *AggregatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedEvent.ProtoReflect.Descriptor instead.
func (*AggregatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{1}
}

func (x *AggregatedEvent) GetGeo() *GeoData {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *AggregatedEvent) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_NONE
}

func (x *AggregatedEvent) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AggregatedEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_proto_livemap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEventsResponse) GetEvents() []*AggregatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_livemap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{3}
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_proto_livemap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{4}
}

type ClassificationCount struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Classification    Classification         `protobuf:"varint,1,opt,name=classification,proto3,enum=livemap.Classification" json:"classification,omitempty"`
	Count             uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // windowed count for trendlines
	MessagesPerSecond float32                `protobuf:"fixed32,3,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`
	AsnCount          uint32                 `protobuf:"varint,4,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	PrefixCount       uint32                 `protobuf:"varint,5,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	Ipv4PrefixCount   uint32                 `protobuf:"varint,7,opt,name=ipv4_prefix_count,json=ipv4PrefixCount,proto3" json:"ipv4_prefix_count,omitempty"`
	Ipv6PrefixCount   uint32                 `protobuf:"varint,8,opt,name=ipv6_prefix_count,json=ipv6PrefixCount,proto3" json:"ipv6_prefix_count,omitempty"`
	Ipv4Count         uint64                 `protobuf:"varint,9,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	TotalCount        uint64                 `protobuf:"varint,10,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // global cumulative total
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassificationCount) Reset() {
	*x = ClassificationCount{}
	mi := &file_proto_livemap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationCount) ProtoMessage() {}

func (x *ClassificationCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationCount.ProtoReflect.Descriptor instead.
func (*ClassificationCount) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{5}
}

func (x *ClassificationCount) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_NONE
}

func (x *ClassificationCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClassificationCount) GetMessagesPerSecond() float32 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *ClassificationCount) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *ClassificationCount) GetPrefixCount() uint32 {
	if x != nil {
		return x.PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv4PrefixCount() uint32 {
	if x != nil {
		return x.Ipv4PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv6PrefixCount() uint32 {
	if x != nil {
		return x.Ipv6PrefixCount
	}
	return 0
}

func (x *ClassificationCount) GetIpv4Count() uint64 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *ClassificationCount) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SummaryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessagesPerSecond    float32                `protobuf:"fixed32,1,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`
	AsnCount             uint32                 `protobuf:"varint,2,opt,name=asn_count,json=asnCount,proto3" json:"asn_count,omitempty"`
	PrefixCount          uint32                 `protobuf:"varint,3,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	ClassificationCounts []*ClassificationCount `protobuf:"bytes,5,rep,name=classification_counts,json=classificationCounts,proto3" json:"classification_counts,omitempty"`
	Ipv4PrefixCount      uint32                 `protobuf:"varint,6,opt,name=ipv4_prefix_count,json=ipv4PrefixCount,proto3" json:"ipv4_prefix_count,omitempty"`
	Ipv6PrefixCount      uint32                 `protobuf:"varint,7,opt,name=ipv6_prefix_count,json=ipv6PrefixCount,proto3" json:"ipv6_prefix_count,omitempty"`
	Ipv4Count            uint64                 `protobuf:"varint,8,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	InputChannelLen      uint32                 `protobuf:"varint,9,opt,name=input_channel_len,json=inputChannelLen,proto3" json:"input_channel_len,omitempty"`
	InputChannelCapacity uint32                 `protobuf:"varint,10,opt,name=input_channel_capacity,json=inputChannelCapacity,proto3" json:"input_channel_capacity,omitempty"`
	MaxLagSeconds        uint32                 `protobuf:"varint,11,opt,name=max_lag_seconds,json=maxLagSeconds,proto3" json:"max_lag_seconds,omitempty"`
	LoadingHistorical    bool                   `protobuf:"varint,12,opt,name=loading_historical,json=loadingHistorical,proto3" json:"loading_historical,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_proto_livemap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{6}
}

func (x *SummaryResponse) GetMessagesPerSecond() float32 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *SummaryResponse) GetAsnCount() uint32 {
	if x != nil {
		return x.AsnCount
	}
	return 0
}

func (x *SummaryResponse) GetPrefixCount() uint32 {
	if x != nil {
		return x.PrefixCount
	}
	return 0
}

func (x *SummaryResponse) GetClassificationCounts() []*ClassificationCount {
	if x != nil {
		return x.ClassificationCounts
	}
	return nil
}

func (x *SummaryResponse) GetIpv4PrefixCount() uint32 {
	if x != nil {
		return x.Ipv4PrefixCount
	}
	return 0
}

func (x *SummaryResponse) GetIpv6PrefixCount() uint32 {
	if x != nil {
		return x.Ipv6PrefixCount
	}
	return 0
}

func (x *SummaryResponse) GetIpv4Count() uint64 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *SummaryResponse) GetInputChannelLen() uint32 {
	if x != nil {
		return x.InputChannelLen
	}
	return 0
}

func (x *SummaryResponse) GetInputChannelCapacity() uint32 {
	if x != nil {
		return x.InputChannelCapacity
	}
	return 0
}

func (x *SummaryResponse) GetMaxLagSeconds() uint32 {
	if x != nil {
		return x.MaxLagSeconds
	}
	return 0
}

func (x *SummaryResponse) GetLoadingHistorical() bool {
	if x != nil {
		return x.LoadingHistorical
	}
	return false
}

type LeakDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeakType         uint32                 `protobuf:"varint,1,opt,name=leak_type,json=leakType,proto3" json:"leak_type,omitempty"` // Maps to LeakType enum in Rust/Go
	LeakerAsn        uint32                 `protobuf:"varint,2,opt,name=leaker_asn,json=leakerAsn,proto3" json:"leaker_asn,omitempty"`
	VictimAsn        uint32                 `protobuf:"varint,3,opt,name=victim_asn,json=victimAsn,proto3" json:"victim_asn,omitempty"`
	LeakerAsName     string                 `protobuf:"bytes,4,opt,name=leaker_as_name,json=leakerAsName,proto3" json:"leaker_as_name,omitempty"`
	VictimAsName     string                 `protobuf:"bytes,5,opt,name=victim_as_name,json=victimAsName,proto3" json:"victim_as_name,omitempty"`
	LeakerRpkiStatus int32                  `protobuf:"varint,6,opt,name=leaker_rpki_status,json=leakerRpkiStatus,proto3" json:"leaker_rpki_status,omitempty"`
	VictimRpkiStatus int32                  `protobuf:"varint,7,opt,name=victim_rpki_status,json=victimRpkiStatus,proto3" json:"victim_rpki_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeakDetail) Reset() {
	*x = LeakDetail{}
	mi := &file_proto_livemap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakDetail) ProtoMessage() {}

func (x *LeakDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakDetail.ProtoReflect.Descriptor instead.
func (*LeakDetail) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{7}
}

func (x *LeakDetail) GetLeakType() uint32 {
	if x != nil {
		return x.LeakType
	}
	return 0
}

func (x *LeakDetail) GetLeakerAsn() uint32 {
	if x != nil {
		return x.LeakerAsn
	}
	return 0
}

func (x *LeakDetail) GetVictimAsn() uint32 {
	if x != nil {
		return x.VictimAsn
	}
	return 0
}

func (x *LeakDetail) GetLeakerAsName() string {
	if x != nil {
		return x.LeakerAsName
	}
	return ""
}

func (x *LeakDetail) GetVictimAsName() string {
	if x != nil {
		return x.VictimAsName
	}
	return ""
}

func (x *LeakDetail) GetLeakerRpkiStatus() int32 {
	if x != nil {
		return x.LeakerRpkiStatus
	}
	return 0
}

func (x *LeakDetail) GetVictimRpkiStatus() int32 {
	if x != nil {
		return x.VictimRpkiStatus
	}
	return 0
}

type StateTransition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Asn           uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	AsName        string                 `protobuf:"bytes,4,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Geo           *GeoData               `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	NewState      Classification         `protobuf:"varint,8,opt,name=new_state,json=newState,proto3,enum=livemap.Classification" json:"new_state,omitempty"`
	OldState      Classification         `protobuf:"varint,9,opt,name=old_state,json=oldState,proto3,enum=livemap.Classification" json:"old_state,omitempty"`
	StartTime     int64                  `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LeakDetail    *LeakDetail            `protobuf:"bytes,12,opt,name=leak_detail,json=leakDetail,proto3" json:"leak_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateTransition) Reset() {
	*x = StateTransition{}
	mi := &file_proto_livemap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransition) ProtoMessage() {}

func (x *StateTransition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransition.ProtoReflect.Descriptor instead.
func (*StateTransition) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{8}
}

func (x *StateTransition) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *StateTransition) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *StateTransition) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *StateTransition) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *StateTransition) GetGeo() *GeoData {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *StateTransition) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StateTransition) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *StateTransition) GetNewState() Classification {
	if x != nil {
		return x.NewState
	}
	return Classification_NONE
}

func (x *StateTransition) GetOldState() Classification {
	if x != nil {
		return x.OldState
	}
	return Classification_NONE
}

func (x *StateTransition) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StateTransition) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StateTransition) GetLeakDetail() *LeakDetail {
	if x != nil {
		return x.LeakDetail
	}
	return nil
}

type StreamStateTransitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetStates  []Classification       `protobuf:"varint,1,rep,packed,name=target_states,json=targetStates,proto3,enum=livemap.Classification" json:"target_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateTransitionsRequest) Reset() {
	*x = StreamStateTransitionsRequest{}
	mi := &file_proto_livemap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateTransitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateTransitionsRequest) ProtoMessage() {}

func (x *StreamStateTransitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateTransitionsRequest.ProtoReflect.Descriptor instead.
func (*StreamStateTransitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{9}
}

func (x *StreamStateTransitionsRequest) GetTargetStates() []Classification {
	if x != nil {
		return x.TargetStates
	}
	return nil
}

type StreamStateTransitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transition    *StateTransition       `protobuf:"bytes,1,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateTransitionsResponse) Reset() {
	*x = StreamStateTransitionsResponse{}
	mi := &file_proto_livemap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateTransitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateTransitionsResponse) ProtoMessage() {}

func (x *StreamStateTransitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livemap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateTransitionsResponse.ProtoReflect.Descriptor instead.
func (*StreamStateTransitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_livemap_proto_rawDescGZIP(), []int{10}
}

func (x *StreamStateTransitionsResponse) GetTransition() *StateTransition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_proto_livemap_proto protoreflect.FileDescriptor

const file_proto_livemap_proto_rawDesc = "" +
	"\n" +
	"\x13proto/livemap.proto\x12\alivemap\"-\n" +
	"\aGeoData\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\"\x8c\x01\n" +
	"\x0fAggregatedEvent\x12\"\n" +
	"\x03geo\x18\x01 \x01(\v2\x10.livemap.GeoDataR\x03geo\x12?\n" +
	"\x0eclassification\x18\x02 \x01(\x0e2\x17.livemap.ClassificationR\x0eclassification\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"H\n" +
	"\x14StreamEventsResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.livemap.AggregatedEventR\x06events\"\x15\n" +
	"\x13StreamEventsRequest\"\x10\n" +
	"\x0eSummaryRequest\"\xf4\x02\n" +
	"\x13ClassificationCount\x12?\n" +
	"\x0eclassification\x18\x01 \x01(\x0e2\x17.livemap.ClassificationR\x0eclassification\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12.\n" +
	"\x13messages_per_second\x18\x03 \x01(\x02R\x11messagesPerSecond\x12\x1b\n" +
	"\tasn_count\x18\x04 \x01(\rR\basnCount\x12!\n" +
	"\fprefix_count\x18\x05 \x01(\rR\vprefixCount\x12*\n" +
	"\x11ipv4_prefix_count\x18\a \x01(\rR\x0fipv4PrefixCount\x12*\n" +
	"\x11ipv6_prefix_count\x18\b \x01(\rR\x0fipv6PrefixCount\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\t \x01(\x04R\tipv4Count\x12\x1f\n" +
	"\vtotal_count\x18\n" +
	" \x01(\x04R\n" +
	"totalCount\"\x84\x04\n" +
	"\x0fSummaryResponse\x12.\n" +
	"\x13messages_per_second\x18\x01 \x01(\x02R\x11messagesPerSecond\x12\x1b\n" +
	"\tasn_count\x18\x02 \x01(\rR\basnCount\x12!\n" +
	"\fprefix_count\x18\x03 \x01(\rR\vprefixCount\x12Q\n" +
	"\x15classification_counts\x18\x05 \x03(\v2\x1c.livemap.ClassificationCountR\x14classificationCounts\x12*\n" +
	"\x11ipv4_prefix_count\x18\x06 \x01(\rR\x0fipv4PrefixCount\x12*\n" +
	"\x11ipv6_prefix_count\x18\a \x01(\rR\x0fipv6PrefixCount\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\b \x01(\x04R\tipv4Count\x12*\n" +
	"\x11input_channel_len\x18\t \x01(\rR\x0finputChannelLen\x124\n" +
	"\x16input_channel_capacity\x18\n" +
	" \x01(\rR\x14inputChannelCapacity\x12&\n" +
	"\x0fmax_lag_seconds\x18\v \x01(\rR\rmaxLagSeconds\x12-\n" +
	"\x12loading_historical\x18\f \x01(\bR\x11loadingHistorical\"\x8f\x02\n" +
	"\n" +
	"LeakDetail\x12\x1b\n" +
	"\tleak_type\x18\x01 \x01(\rR\bleakType\x12\x1d\n" +
	"\n" +
	"leaker_asn\x18\x02 \x01(\rR\tleakerAsn\x12\x1d\n" +
	"\n" +
	"victim_asn\x18\x03 \x01(\rR\tvictimAsn\x12$\n" +
	"\x0eleaker_as_name\x18\x04 \x01(\tR\fleakerAsName\x12$\n" +
	"\x0evictim_as_name\x18\x05 \x01(\tR\fvictimAsName\x12,\n" +
	"\x12leaker_rpki_status\x18\x06 \x01(\x05R\x10leakerRpkiStatus\x12,\n" +
	"\x12victim_rpki_status\x18\a \x01(\x05R\x10victimRpkiStatus\"\xa3\x03\n" +
	"\x0fStateTransition\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12\x17\n" +
	"\aas_name\x18\x04 \x01(\tR\x06asName\x12\"\n" +
	"\x03geo\x18\x05 \x01(\v2\x10.livemap.GeoDataR\x03geo\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x124\n" +
	"\tnew_state\x18\b \x01(\x0e2\x17.livemap.ClassificationR\bnewState\x124\n" +
	"\told_state\x18\t \x01(\x0e2\x17.livemap.ClassificationR\boldState\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x124\n" +
	"\vleak_detail\x18\f \x01(\v2\x13.livemap.LeakDetailR\n" +
	"leakDetail\"]\n" +
	"\x1dStreamStateTransitionsRequest\x12<\n" +
	"\rtarget_states\x18\x01 \x03(\x0e2\x17.livemap.ClassificationR\ftargetStates\"Z\n" +
	"\x1eStreamStateTransitionsResponse\x128\n" +
	"\n" +
	"transition\x18\x01 \x01(\v2\x18.livemap.StateTransitionR\n" +
	"transition*\xa6\x01\n" +
	"\x0eClassification\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05BOGON\x10\x01\x12\n" +
	"\n" +
	"\x06HIJACK\x10\x02\x12\x0e\n" +
	"\n" +
	"ROUTE_LEAK\x10\x03\x12\n" +
	"\n" +
	"\x06OUTAGE\x10\x04\x12\x13\n" +
	"\x0fDDOS_MITIGATION\x10\x05\x12\b\n" +
	"\x04FLAP\x10\x06\x12\x17\n" +
	"\x13TRAFFIC_ENGINEERING\x10\a\x12\x10\n" +
	"\fPATH_HUNTING\x10\b\x12\r\n" +
	"\tDISCOVERY\x10\t2\x89\x02\n" +
	"\aLiveMap\x12P\n" +
	"\x0fSubscribeEvents\x12\x1c.livemap.StreamEventsRequest\x1a\x1d.livemap.StreamEventsResponse0\x01\x12?\n" +
	"\n" +
	"GetSummary\x12\x17.livemap.SummaryRequest\x1a\x18.livemap.SummaryResponse\x12k\n" +
	"\x16StreamStateTransitions\x12&.livemap.StreamStateTransitionsRequest\x1a'.livemap.StreamStateTransitionsResponse0\x01B\x85\x01\n" +
	"\vcom.livemapB\fLivemapProtoP\x01Z,github.com/sudorandom/bgp-stream/pkg/livemap\xa2\x02\x03LXX\xaa\x02\aLivemap\xca\x02\aLivemap\xe2\x02\x13Livemap\\GPBMetadata\xea\x02\aLivemapb\x06proto3"

var (
	file_proto_livemap_proto_rawDescOnce sync.Once
	file_proto_livemap_proto_rawDescData []byte
)

func file_proto_livemap_proto_rawDescGZIP() []byte {
	file_proto_livemap_proto_rawDescOnce.Do(func() {
		file_proto_livemap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_livemap_proto_rawDesc), len(file_proto_livemap_proto_rawDesc)))
	})
	return file_proto_livemap_proto_rawDescData
}

var file_proto_livemap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_livemap_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_livemap_proto_goTypes = []any{
	(Classification)(0),                    // 0: livemap.Classification
	(*GeoData)(nil),                        // 1: livemap.GeoData
	(*AggregatedEvent)(nil),                // 2: livemap.AggregatedEvent
	(*StreamEventsResponse)(nil),           // 3: livemap.StreamEventsResponse
	(*StreamEventsRequest)(nil),            // 4: livemap.StreamEventsRequest
	(*SummaryRequest)(nil),                 // 5: livemap.SummaryRequest
	(*ClassificationCount)(nil),            // 6: livemap.ClassificationCount
	(*SummaryResponse)(nil),                // 7: livemap.SummaryResponse
	(*LeakDetail)(nil),                     // 8: livemap.LeakDetail
	(*StateTransition)(nil),                // 9: livemap.StateTransition
	(*StreamStateTransitionsRequest)(nil),  // 10: livemap.StreamStateTransitionsRequest
	(*StreamStateTransitionsResponse)(nil), // 11: livemap.StreamStateTransitionsResponse
}
var file_proto_livemap_proto_depIdxs = []int32{
	1,  // 0: livemap.AggregatedEvent.geo:type_name -> livemap.GeoData
	0,  // 1: livemap.AggregatedEvent.classification:type_name -> livemap.Classification
	2,  // 2: livemap.StreamEventsResponse.events:type_name -> livemap.AggregatedEvent
	0,  // 3: livemap.ClassificationCount.classification:type_name -> livemap.Classification
	6,  // 4: livemap.SummaryResponse.classification_counts:type_name -> livemap.ClassificationCount
	1,  // 5: livemap.StateTransition.geo:type_name -> livemap.GeoData
	0,  // 6: livemap.StateTransition.new_state:type_name -> livemap.Classification
	0,  // 7: livemap.StateTransition.old_state:type_name -> livemap.Classification
	8,  // 8: livemap.StateTransition.leak_detail:type_name -> livemap.LeakDetail
	0,  // 9: livemap.StreamStateTransitionsRequest.target_states:type_name -> livemap.Classification
	9,  // 10: livemap.StreamStateTransitionsResponse.transition:type_name -> livemap.StateTransition
	4,  // 11: livemap.LiveMap.SubscribeEvents:input_type -> livemap.StreamEventsRequest
	5,  // 12: livemap.LiveMap.GetSummary:input_type -> livemap.SummaryRequest
	10, // 13: livemap.LiveMap.StreamStateTransitions:input_type -> livemap.StreamStateTransitionsRequest
	3,  // 14: livemap.LiveMap.SubscribeEvents:output_type -> livemap.StreamEventsResponse
	7,  // 15: livemap.LiveMap.GetSummary:output_type -> livemap.SummaryResponse
	11, // 16: livemap.LiveMap.StreamStateTransitions:output_type -> livemap.StreamStateTransitionsResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_livemap_proto_init() }
func file_proto_livemap_proto_init() {
	if File_proto_livemap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_livemap_proto_rawDesc), len(file_proto_livemap_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_livemap_proto_goTypes,
		DependencyIndexes: file_proto_livemap_proto_depIdxs,
		EnumInfos:         file_proto_livemap_proto_enumTypes,
		MessageInfos:      file_proto_livemap_proto_msgTypes,
	}.Build()
	File_proto_livemap_proto = out.File
	file_proto_livemap_proto_goTypes = nil
	file_proto_livemap_proto_depIdxs = nil
}
